///////////////////////////////////////////////////////////
//  CxbDevPbDkq.cs
//  Implementation of the Class CxbDevPbDkq
//  Generated by Enterprise Architect
//  Created on:      09-5ÔÂ-2017 17:08:10
//  Original author: open2
///////////////////////////////////////////////////////////

namespace Hvdc.MT.xb.Device
{
    /// <summary>
    /// Æ½²¨µç¿¹Æ÷
    /// </summary>
    public class CxbDevPbDkq : CxbDevBranch
    {

    }//end CxbDevPbDkq

}//end namespace xbDev