///////////////////////////////////////////////////////////
//  CxbDev3pVSrccs
//  Implementation of the Class CxbDev3pVSrc
//  Generated by Enterprise Architect
//  Created on:      09-5月-2017 17:08:09
//  Original author: open2
///////////////////////////////////////////////////////////

using Hvdc.MT.xb.Def;

namespace Hvdc.MT.xb.Device
{
    /// <summary>
    /// 三脉动电压源，
    /// 只在三脉动电压源计算中考虑
    /// 直流谐波计算中暂时不用考虑
    /// </summary>
    public class CxbDev3pVSrc : CxbDevTwoDot
    {
        public CxbDev3pVSrc()
        {
            hUrms = new double[CxbDef.hMax];
            hAngle = new double[CxbDef.hMax];
         
            hYb = new double[CxbDef.hMax];
        }

        public double[] hUrms;
        public double[] hAngle;
        public double[] hYb;


    }//end CxbDev3pVSrc

}//end namespace xbDev