///////////////////////////////////////////////////////////
//  CxbDevCouple_C.cs
//  Implementation of the Class CxbDevCouple_C
//  Generated by Enterprise Architect
//  Created on:      09-5ÔÂ-2017 17:08:09
//  Original author: open2
///////////////////////////////////////////////////////////

namespace Hvdc.MT.xb.Device
{
    /// <summary>
    /// ñîºÏµçÈÝ
    /// </summary>
    public class CxbDevCouple_C : CxbDevShunt
    {

    }//end CxbDevCouple_C

}//end namespace xbDev