///////////////////////////////////////////////////////////
//  CmcVars.cs
//  Implementation of the Class CmcVars
//  Generated by Enterprise Architect
//  Created on:      09-5ÔÂ-2017 16:17:29
//  Original author: open2
///////////////////////////////////////////////////////////

using System;
using Hvdc.MT.mc.DevTBL;
using Hvdc.MT.mc.Solve;
using System.Collections.Generic;

namespace Hvdc.MT.mc.App
{
    public static class CmcVars
    {
        public static CmcOrder  pOrder;
        public static CmcResult pResult;

        public static CmcHvdcGrid pmcHvdcGrid;


        public static void Init()
        {
            pmcHvdcGrid = new CmcHvdcGrid();

            pOrder = new CmcOrder();

            pResult = new CmcResult();

        }
        public static void Release()
        {
            //pmcHvdcGrid.Release();
        }

        public static void Clear()
        {
            pmcHvdcGrid.Clear();
        }

        public static void NewGrid()
        {
            List<string> StaNames = new List<string>();

            StaNames.Add("station1");
            StaNames.Add("station2");
            StaNames.Add("station3");
            
            pmcHvdcGrid.NewGrid(StaNames);

        }
    }//end CmcVars

}//end namespace mc