///////////////////////////////////////////////////////////
//  CmcCase.cs
//  Implementation of the Class CmcCase
//  Generated by Enterprise Architect
//  Created on:      29-5ÔÂ-2017 16:11:11
//  Original author: open2
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Hvdc.MT.HvdcCommon
{
    public class CmcCase
    {

        IList<RecResultData> pDataList = new List<RecResultData>();

        public string DataName;
        public string StationName;

        public virtual void Init()
        {
        }
        public virtual void Clear()
        {
            pDataList.Clear();            
        }

        public void AddRecord(RecResultData vData)
        {
            pDataList.Add(vData);
        }

        public virtual bool IsLeaf()
        {
            return true;
        }

        public virtual void Add(CmcCase vItem)
        {

        }

        public virtual void Remove(CmcCase vItem)
        {

        }

        public IList<RecResultData> DataList()
        {
            return pDataList;
        }

    }//end CmcCase

}//end namespace HvdcCommon