///////////////////////////////////////////////////////////
//  CmcOrder.cs
//  Implementation of the Class CmcOrder
//  Generated by Enterprise Architect
//  Created on:      27-5月-2017 9:49:58
//  Original author: open2
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Hvdc.MT.HvdcCommon;

namespace Hvdc.MT.xb.Solve
{
    public class CxbOrder : CHvdcOrder
    {
        public List<RecResultData> mcData = new List<RecResultData>();


        /// <summary>
        /// 12脉动中间是否接地
        /// </summary>
        public int Is6Pulse = 0;

        /// <summary>
        /// 计算方式，0=性能计算;1=定值计算，默认1
        /// </summary>
        public int CalcType = 1;

        /// <summary>
        /// 单回结果方式，0=多对单;1=多对多，默认1
        /// </summary>
        public int SingleReusltType = 0;

        /// <summary>
        /// 加权方式，0=P加权;1=C加权;2=不加权
        /// </summary>
        public int Plus = 0;

        public override void Init()
        {
            base.Init();           
        }

    }//end CxbOrder

}//end namespace HvdcCommon