///////////////////////////////////////////////////////////
//  CmcOrder.cs
//  Implementation of the Class CmcOrder
//  Generated by Enterprise Architect
//  Created on:      27-5月-2017 9:49:58
//  Original author: open2
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Hvdc.MT.HvdcCommon;

namespace Hvdc.MT.xb.Solve
{
    public class CzkOrder : CHvdcOrder
    {
        /// <summary>
        /// 12脉动中间是否接地
        /// </summary>
        public int Is6Pulse = 0;

        /// <summary>
        /// 开始频率
        /// </summary>
        public double FreqStart;

        /// <summary>
        /// 计算数量
        /// </summary>
        public int FreqDim;

        /// <summary>
        /// 频率步长
        /// </summary>
        public double FreqStep;

        public override void Init()
        {
            base.Init();           
        }

    }//end CxbOrder

}//end namespace HvdcCommon