///////////////////////////////////////////////////////////
//  CxbFunc.cs
//  Implementation of the Class CxbFunc
//  Generated by Enterprise Architect
//  Created on:      09-5月-2017 16:15:35
//  Original author: open2
///////////////////////////////////////////////////////////


using Hvdc.MT.xb.Def;

namespace Hvdc.MT.xb.Func
{
    public static class CxbFunc
    {

        /// 
        /// <param name="vType"></param>
        public static string xbTypeToName(int vType)
        {
            string vStr;

            //Yao_xb: 
            switch (vType)
            {
                case CxbDef.xb_3pVSrc:
                    vStr = "3脉动电压源";
                    break;

                case CxbDef.xb_PbDKQ:
                    vStr = "平波电抗器";
                    break;

                case CxbDef.xb_DCF:
                    vStr = "直流滤波器";
                    break;

                case CxbDef.xb_DCF_RLC:
                    vStr = "直流滤波器RLC";
                    break;

                case CxbDef.xb_DCLine:
                    vStr = "直流极线";
                    break;

                case CxbDef.xb_GroundLine:
                    vStr = "接地极线";
                    break;

                case CxbDef.xb_DcLine_Seg:
                    vStr = "直流极线Seg";
                    break;

                case CxbDef.xb_GroundLine_Seg:
                    vStr = "接地极线Seg";
                    break;

                case CxbDef.xb_Ground:
                    vStr = "接地电阻";
                    break;

                case CxbDef.xb_MetalLine:
                    vStr = "金属回线";
                    break;

                case CxbDef.xb_XfC:
                    vStr = "杂散电容";
                    break;

                case CxbDef.xb_CoupleC:
                    vStr = "耦合电容器";
                    break;

                case CxbDef.xb_PulseC:
                    vStr = "冲激电容器";
                    break;

                case CxbDef.xb_Shunt:
                    vStr = "并联支路";
                    break;

                case CxbDef.xb_Branch:
                    vStr = "串联支路";
                    break;

                case CxbDef.xb_Trap:
                    vStr = "阻波器";
                    break;

                case CxbDef.xb_Monitor:
                    vStr = "监控装置";
                    break;

                default:
                    vStr = "xbDevice";
                    break;

            }//switch

            return vStr;

        }

    }//end CxbFunc

}//end namespace xb