///////////////////////////////////////////////////////////
//  C3pParams.cs
//  Implementation of the Class C3pParams
//  Generated by Enterprise Architect
//  Created on:      09-5ÔÂ-2017 16:15:35
//  Original author: open2
///////////////////////////////////////////////////////////

using Yao.BaseFrame.App;

namespace Hvdc.MT.U3p.App
{
    public static class C3pParams
    {
        public static string dbfFile { get; set; }

        public static int mcStationCount { set; get; }
     
        public static void Clear()
        {
        }
       

        public static void Init()
        {
            mcStationCount = 2;

            //
            dbfFile = "..\\..\\..\\..\\DBF\\U3pDBF.accdb";

        }
    }//end C3pParams

}//end namespace mc