///////////////////////////////////////////////////////////
//  CxbDevGroundLine.cs
//  Implementation of the Class CxbDevGroundLine
//  Generated by Enterprise Architect
//  Created on:      09-5月-2017 17:08:10
//  Original author: open2
///////////////////////////////////////////////////////////

namespace Hvdc.MT.xb.Device
{
    /// <summary>
    /// 接地线路，可能含多个子段
    /// </summary>
    public class CxbDevGroundLine : CxbDev_Tree
    {

    }//end CxbDevGroundLine

}//end namespace xbDev