///////////////////////////////////////////////////////////
//  CxbDevMonitor.cs
//  Implementation of the Class CxbDevMonitor
//  Generated by Enterprise Architect
//  Created on:      09-5月-2017 17:08:10
//  Original author: open2
///////////////////////////////////////////////////////////

namespace Hvdc.MT.xb.Device
{
    /// <summary>
    /// 监控装置组合,含有多个branch子设备
    /// </summary>
    public class CxbDevMonitor : CxbDev_Tree
    {

    }//end CxbDevMonitor

}//end namespace xbDev