///////////////////////////////////////////////////////////
//  CmcOrder.cs
//  Implementation of the Class CmcOrder
//  Generated by Enterprise Architect
//  Created on:      27-5月-2017 9:49:58
//  Original author: open2
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Hvdc.MT.HvdcCommon;

namespace Hvdc.MT.U3p.Solve
{
    public class C3pOrder : CHvdcOrder
    {
        /// <summary>
        /// 12脉动中间是否接地
        /// </summary>
        public int Is6Pulse;

        /// <summary>
        /// 偏差输入方式0=手动，1=自动，2=概率
        /// </summary>
        public int DltType;

        /// <summary>
        /// 直流电流偏差
        /// </summary>
        public double DcIdDlt;


       /// <summary>
       /// 直流电压偏差
       /// </summary>
        public double DcUdDlt;

        /// <summary>
        /// 概率统计算法次数
        /// </summary>
        public int ProStdCount;

        /// <summary>
        /// 是否保守处理结果1=是;0=否
        /// </summary>
        public int ConResult;

        public override void Init()
        {
            base.Init();
        }

    }//end C3pOrder

}//end namespace HvdcCommon