///////////////////////////////////////////////////////////
//  C3pRwTwo.cs
//  Implementation of the class C3pRwTwo
//  Generated by Enterprise Architect
//  Created on:      09-5ÔÂ-2017 8:08:05
//  Original author: open2
///////////////////////////////////////////////////////////

using Hvdc.MT.U3p.Device;
using Yao.BaseFrame.Func;

namespace Hvdc.MT.U3p.Rw
{
    public class C3pRwTwo : C3pRw
    {
    }//end C3pRwTwo

}//end namespace mc