///////////////////////////////////////////////////////////
//  C3pRwOne.cs
//  Implementation of the class C3pRwOne
//  Generated by Enterprise Architect
//  Created on:      09-5ÔÂ-2017 8:08:05
//  Original author: open2
///////////////////////////////////////////////////////////

using Hvdc.MT.U3p.Device;
using Yao.BaseFrame.Func;

namespace Hvdc.MT.U3p.Rw
{
    public class C3pRwOne : C3pRw
    {

    }//end C3pRwOne

}//end namespace mc