///////////////////////////////////////////////////////////
//  CmcDevGroundLine.cs
//  Implementation of the Class CmcDevGroundLine
//  Generated by Enterprise Architect
//  Created on:      09-5月-2017 17:08:08
//  Original author: open2
///////////////////////////////////////////////////////////




namespace Hvdc.MT.mc.Device
{
    /// <summary>
    /// 主回路 接地极
    /// </summary>
    public class CmcDevGroundLine : CmcDevDcLine
    {
        public CmcDevGroundLine()
        {
            StaCount = 1;
            dotCount = 2;
        }

    }//end CmcDevGroundLine

}//end namespace mcDev