///////////////////////////////////////////////////////////
//  CxbDeviceTBL.cs
//  Implementation of the Class CxbDeviceTBL
//  Generated by Enterprise Architect
//  Created on:      09-5月-2017 17:08:10
//  Original author: open2
///////////////////////////////////////////////////////////


using Yao.BaseFrame.Device;
using Yao.BaseFrame.DevTBL;

using Hvdc.MT.xb.Def;
using Hvdc.MT.xb.Device;
using Hvdc.MT.xb.Func;

namespace Hvdc.MT.xb.DevTBL
{
    /// <summary>
    /// xb直流设备表
    /// </summary>
    public class CxbDeviceTBL : CDevTBL
    {
        public override string TypeToName(int vType)
        {

            return CxbFunc.xbTypeToName(vType);
        }


        /// 
        /// <param name="vDevType"></param>
        protected override CDevBase doNewDevice(int vDevType)
        {
            return xbNewDevice(vDevType);
        }

        /// 
        /// <param name="vDevType"></param>
        public static CDevBase xbNewDevice(int vDevType)
        {

            CDevBase vDev;

            switch (vDevType)
            {
                case CxbDef.xb_3pVSrc:
                    vDev = new CxbDev3pVSrc();
                    break;

                case CxbDef.xb_PbDKQ:
                    vDev = new CxbDevPbDkq();
                    break;

                case CxbDef.xb_DCF:
                    vDev = new CxbDevDCF();
                    break;

                case CxbDef.xb_DCF_RLC:
                    vDev = new CxbDevDCF_RLC();
                    break;

                case CxbDef.xb_DCLine:
                    vDev = new CxbDevDcLine();
                    break;

                case CxbDef.xb_GroundLine:
                    vDev = new CxbDevGroundLine();
                    break;

                case CxbDef.xb_DcLine_Seg:
                    vDev = new CxbDevDcLine_Seg();
                    break;

                case CxbDef.xb_GroundLine_Seg:
                    vDev = new CxbDevGroundLine_Seg();
                    break;

                case CxbDef.xb_Ground:
                    vDev = new CxbDevGround();
                    break;

                //case CxbDef.xb_MetalLine:
                //vDev = new CxbDevMetalLine();
                //break;

                case CxbDef.xb_XfC:
                    vDev = new CxbDevXf_C();
                    break;

                case CxbDef.xb_CoupleC:
                    vDev = new CxbDevCouple_C();
                    break;

                case CxbDef.xb_PulseC:
                    vDev = new CxbDevPulse_C();
                    break;

                case CxbDef.xb_Shunt:
                    vDev = new CxbDevShunt();
                    break;

                case CxbDef.xb_Branch:
                    vDev = new CxbDevBranch();
                    break;

                case CxbDef.xb_Trap:
                    vDev = new CxbDevTrap();
                    break;

                case CxbDef.xb_Monitor:
                    vDev = new CxbDevMonitor();
                    break;

                default:
                    vDev = new CxbDevBase();
                    break;

            }//switch

            vDev.Init();

            return vDev;
        }

    }//end CxbDeviceTBL

}//end namespace DevTBL