///////////////////////////////////////////////////////////
//  CxbHvdcGrid.cs
//  Implementation of the Class CxbHvdcGrid
//  Generated by Enterprise Architect
//  Created on:      09-5ÔÂ-2017 17:08:10
//  Original author: open2
///////////////////////////////////////////////////////////


using Yao.BaseFrame.DevTBL;

using Hvdc.MT.xb.Def;
using Hvdc.MT.xb.Func;
using Yao.BaseFrame.Device;
using System;
using System.Collections.Generic;

namespace Hvdc.MT.xb.DevTBL
{
    public class CxbHvdcGrid : CDevGrid
    {

        public override void Init()
        {
            int i1, i2;

            i1 = CxbDef.xb_3pVSrc;
            i2 = CxbDef.xb_GroundLine;

            for (int i = i1; i <= i2; i++)
                NewDevTBL(i);
        }

        /// 
        /// <param name="vType"></param>
        public override string TypeToName(int vType)
        {

            return CxbFunc.xbTypeToName(vType);
        }

        /// 
        /// <param name="vType"></param>
        public override CDevTBL NewDevTBL(int vType)
        {

            string vName;
            CDevTBL vTBL;

            vName = TypeToName(vType);

            //
            vTBL = new CxbDevTBL();
            vTBL.tblName = vName;
            vTBL.tblType = vType;

            //
            Add(vTBL);

            //
            pTables[vType] = vTBL;

            return vTBL;
        }

        protected override CDevStation doNewStation()
        {
            return new CxbDevStation();
        }

        public void NewGrid(List<string> vStations)
        {
            //Âí¿¡Åô
        }

    }//end CxbHvdcGrid

}//end namespace DevTBL