///////////////////////////////////////////////////////////
//  CmcRwShunt.cs
//  Implementation of the class CmcRwShunt
//  Generated by Enterprise Architect
//  Created on:      09-5ÔÂ-2017 8:08:05
//  Original author: open2
///////////////////////////////////////////////////////////


using Hvdc.MT.mc.dataRw;
using Hvdc.MT.mc.Device;
using Yao.BaseFrame.Device;

namespace Hvdc.MT.mc.Rw
{
    public class CmcDataRwDcLine : CmcDataRwTwo
    {
        protected override void doLoad(CDevBase vDevice)
        {
            CmcDevDcLine vDev;
            vDev = (CmcDevDcLine)vDevice;

            base.doLoad(vDevice);

            
            vDev.Zr = RwAdo.ReadDouble("ZrN") ;
            
            vDev.ZrMax = RwAdo.ReadDouble("ZrMax") ;
            vDev.ZrMin = RwAdo.ReadDouble("ZrMin") ;            

        }

        /// 
        /// <param name="vDevice"></param>
        protected override void doSave(CDevBase vDevice)
        {
            CmcDevDcLine vDev;
            vDev = (CmcDevDcLine)vDevice;

            base.doSave(vDevice);
            
            RwAdo.SaveField("ZrN",vDev.ZrN) ;
             
            RwAdo.SaveField("ZrMax", vDev.ZrMax) ;
            RwAdo.SaveField("ZrMin", vDev.ZrMin) ;
          

        }

    }//end CmcRwShunt
}//end namespace mc