///////////////////////////////////////////////////////////
//  CHvdcVars.cs
//  Implementation of the Class CHvdcVars
//  Generated by Enterprise Architect
//  Created on:      09-5ÔÂ-2017 16:15:35
//  Original author: open2
///////////////////////////////////////////////////////////

using Hvdc.MT.mc.App;
using Hvdc.MT.U3p.App;
using Hvdc.MT.xb.App;

namespace Hvdc.MT.Project.App
{
    public static class CHvdcVars
    {
        public static void Init()
        {
            CmcVars.Init();
            CxbVars.Init();

            C3pVars.Init();

        }
        public static void Release()
        {
            CmcVars.Release();
            CxbVars.Release();

            C3pVars.Release();

        }

        public static void Clear()
        {
            CmcVars.Clear();
            CxbVars.Clear();

            C3pVars.Clear();
        }       

    }//end CHvdcVars

}//end namespace BaseFrame