///////////////////////////////////////////////////////////
//  CxbRwMvc.cs
//  Implementation of the Class CxbRwMvc
//  Generated by Enterprise Architect
//  Created on:      09-5ÔÂ-2017 8:08:07
//  Original author: open2
///////////////////////////////////////////////////////////


using Yao.BaseFrame.Rw;
using Hvdc.MT.xb.Def;
using Hvdc.MT.xb.DevTBL;
using Hvdc.MT.xb.Rw;

namespace Hvdc.MT.xb.RwMvc
{
    public class CxbRwMvc : CRwMvcAccess
    {
        protected CxbHvdcGrid pHvdc;

        /// 
        /// <param name="vHvdc"></param>
        public void InitGrid(CxbHvdcGrid vHvdc)
        {
            pHvdc = vHvdc;
        }

        protected override void doLoad()
        {
            doLoad_xb3pVSrc();

            doLoad_xbPbDKQ();

            doLoad_xbGround();
            doLoad_xbXfC();
            doLoad_xbCoupleC();
            doLoad_xbPulseC();
            doLoad_xbShunt();
            doLoad_xbBranch();

            doLoad_xbMonitor();
            doLoad_xbTrap();

            doLoad_xbDCF();

            doLoad_xbDcLine();
            doLoad_xbGroundLine();

        }

        protected override void doSave()
        {
            doSave_xb3pVSrc();

            doSave_xbPbDKQ();
            doSave_xbGround();

            doSave_xbXfC();
            doSave_xbCoupleC();
            doSave_xbPulseC();

            doSave_xbShunt();
            doSave_xbBranch();

            doSave_xbMonitor();
            doSave_xbTrap();

            //
            doSave_xbDCF();

            doSave_xbDcLine();
            doSave_xbGroundLine();

        }

        protected override void doLoad(int vtblType)
        {
            switch (vtblType)
            {
                case CxbDef.xb_3pVSrc:
                    doLoad_xb3pVSrc();
                    break;

                case CxbDef.xb_PbDKQ:
                    doLoad_xbPbDKQ();
                    break;

                case CxbDef.xb_DCF:
                    doLoad_xbDCF();
                    break;
               
                case CxbDef.xb_DCLine:
                    doLoad_xbDcLine();
                    break;

                case CxbDef.xb_GroundLine:
                    doLoad_xbGroundLine();
                    break;

                case CxbDef.xb_Ground:
                    doLoad_xbGround();
                    break;

                //case CxbDef.xb_MetalLine:
                //doLoad_xbMetalLine();
                //break;

                case CxbDef.xb_XfC:
                    doLoad_xbXfC();
                    break;

                case CxbDef.xb_CoupleC:
                    doSave_xbCoupleC();
                    break;

                case CxbDef.xb_PulseC:
                    doLoad_xbPulseC();
                    break;

                case CxbDef.xb_Shunt:
                    doLoad_xbShunt();
                    break;

                case CxbDef.xb_Branch:
                    doLoad_xbBranch();
                    break;

                case CxbDef.xb_Trap:
                    doLoad_xbTrap();
                    break;

                case CxbDef.xb_Monitor:
                    doLoad_xbMonitor();
                    break;

                default:
                    //
                    break;

            }//switch

        }


        protected override void doSave(int vtblType)
        {
            switch (vtblType)
            {
                case CxbDef.xb_3pVSrc:
                    doSave_xb3pVSrc();
                    break;

                case CxbDef.xb_PbDKQ:
                    doSave_xbPbDKQ();
                    break;

                case CxbDef.xb_DCF:
                    doSave_xbDCF();
                    break;

                case CxbDef.xb_DCLine:
                    doSave_xbDcLine();
                    break;

                case CxbDef.xb_GroundLine:
                    doSave_xbGroundLine();
                    break;

                case CxbDef.xb_Ground:
                    doSave_xbGround();
                    break;

                //case CxbDef.xb_MetalLine:
                //doSave_xbMetalLine();
                //break;

                case CxbDef.xb_XfC:
                    doSave_xbXfC();
                    break;

                case CxbDef.xb_CoupleC:
                    doSave_xbCoupleC();
                    break;

                case CxbDef.xb_PulseC:
                    doSave_xbPulseC();
                    break;

                case CxbDef.xb_Shunt:
                    doSave_xbShunt();
                    break;

                case CxbDef.xb_Branch:
                    doSave_xbBranch();
                    break;

                case CxbDef.xb_Trap:
                    doSave_xbTrap();
                    break;

                case CxbDef.xb_Monitor:
                    doSave_xbMonitor();
                    break;

                default:
                    //
                    break;

            }//switch

        }

        protected void doLoad_xb3pVSrc()
        {

            CxbRw3pVSrc vRw = new CxbRw3pVSrc();

            vRw.InitAdo(RwAdo);
            vRw.InitTable("xb3pVsrc");
            vRw.InitType(CxbDef.xb_3pVSrc, CxbDef.xb_3pVSrc);
            vRw.InitGrid(pHvdc);

            vRw.OnLoad();
        }

        protected void doLoad_xbPbDKQ()
        {
            CxbRwBranch vRw = new CxbRwBranch();

            vRw.InitAdo(RwAdo);
            vRw.InitTable("xbPbDKQ");
            vRw.InitType(CxbDef.xb_PbDKQ, CxbDef.xb_PbDKQ);
            vRw.InitGrid(pHvdc);

            vRw.OnLoad();
        }

        protected void doLoad_xbDCF()
        {

            CxbRwDCF vRw = new CxbRwDCF();

            vRw.InitAdo(RwAdo);
            vRw.InitTable("xbDCF", "xbDCF_tree", "xbDCF_tree");
            vRw.InitType(CxbDef.xb_DCF, CxbDef.xb_DCF);
            vRw.InitGrid(pHvdc);

            vRw.OnLoad();
        }

        protected void doLoad_xbDcLine()
        {

            CxbRwDcLine vRw = new CxbRwDcLine();

            vRw.InitAdo(RwAdo);
            vRw.InitTable("xbDcLine", "xbDcLine_tree", "xbDcLine_tree");
            vRw.InitType(CxbDef.xb_DCLine, CxbDef.xb_DCLine);
            vRw.InitGrid(pHvdc);

            vRw.OnLoad();
        }

        protected void doLoad_xbGroundLine()
        {

            CxbRwGroundLine vRw = new CxbRwGroundLine();

            vRw.InitAdo(RwAdo);
            vRw.InitTable("xbGroundLine", "xbGroundLine_tree", "xbGroundLine_tree");
            vRw.InitType(CxbDef.xb_GroundLine, CxbDef.xb_GroundLine);
            vRw.InitGrid(pHvdc);

            vRw.OnLoad();
        }

        protected void doLoad_xbGround()
        {

            CxbRwShunt vRw = new CxbRwShunt();

            vRw.InitAdo(RwAdo);
            vRw.InitTable("xbGround");
            vRw.InitType(CxbDef.xb_Ground, CxbDef.xb_Ground);
            vRw.InitGrid(pHvdc);

            vRw.OnLoad();
        }

        protected void doLoad_xbXfC()
        {

            CxbRwShunt vRw = new CxbRwShunt();

            vRw.InitAdo(RwAdo);
            vRw.InitTable("xbXf_C");
            vRw.InitType(CxbDef.xb_XfC, CxbDef.xb_XfC);
            vRw.InitGrid(pHvdc);

            vRw.OnLoad();
        }

        protected void doLoad_xbCoupleC()
        {

            CxbRwShunt vRw = new CxbRwShunt();

            vRw.InitAdo(RwAdo);
            vRw.InitTable("xbCouple_C");
            vRw.InitType(CxbDef.xb_CoupleC, CxbDef.xb_CoupleC);
            vRw.InitGrid(pHvdc);

            vRw.OnLoad();
        }

        protected void doLoad_xbPulseC()
        {

            CxbRwShunt vRw = new CxbRwShunt();

            vRw.InitAdo(RwAdo);
            vRw.InitTable("xbPulse_C");
            vRw.InitType(CxbDef.xb_PulseC, CxbDef.xb_PulseC);
            vRw.InitGrid(pHvdc);

            vRw.OnLoad();
        }

        protected void doLoad_xbShunt()
        {

            CxbRwShunt vRw = new CxbRwShunt();

            vRw.InitAdo(RwAdo);
            vRw.InitTable("xbShunt");
            vRw.InitType(CxbDef.xb_Shunt, CxbDef.xb_Shunt);
            vRw.InitGrid(pHvdc);

            vRw.OnLoad();
        }

        protected void doLoad_xbBranch()
        {

            CxbRwBranch vRw = new CxbRwBranch();

            vRw.InitAdo(RwAdo);
            vRw.InitTable("xbBranch");
            vRw.InitType(CxbDef.xb_Branch, CxbDef.xb_Branch);
            vRw.InitGrid(pHvdc);

            vRw.OnLoad();
        }

        protected void doLoad_xbMonitor()
        {

            CxbRwRLCs vRw = new CxbRwRLCs();

            vRw.InitAdo(RwAdo);
            vRw.InitTable("xbMonitor", "xbMonitor_tree", "xbMonitor_tree");
            vRw.InitType(CxbDef.xb_Monitor, CxbDef.xb_Monitor);
            vRw.InitGrid(pHvdc);

            vRw.OnLoad();
        }

        protected void doLoad_xbTrap()
        {

            CxbRwRLCs vRw = new CxbRwRLCs();

            vRw.InitAdo(RwAdo);
            vRw.InitTable("xbTrap", "xbTrap_tree", "xbTrap_tree");
            vRw.InitType(CxbDef.xb_Trap, CxbDef.xb_Trap);
            vRw.InitGrid(pHvdc);

            vRw.OnLoad();
        }


        protected void doSave_xb3pVSrc()
        {

            CxbRw3pVSrc vRw = new CxbRw3pVSrc();

            vRw.InitAdo(RwAdo);
            vRw.InitTable("xb3pVsrc");
            vRw.InitType(CxbDef.xb_3pVSrc, CxbDef.xb_3pVSrc);
            vRw.InitGrid(pHvdc);

            vRw.OnSave();
        }

        protected void doSave_xbPbDKQ()
        {
            CxbRwBranch vRw = new CxbRwBranch();

            vRw.InitAdo(RwAdo);
            vRw.InitTable("xbPbDKQ");
            vRw.InitType(CxbDef.xb_PbDKQ, CxbDef.xb_PbDKQ);
            vRw.InitGrid(pHvdc);

            vRw.OnSave();
        }

        protected void doSave_xbDCF()
        {

            CxbRwDCF vRw = new CxbRwDCF();

            vRw.InitAdo(RwAdo);
            vRw.InitTable("xbDCF", "xbDCF_tree", "xbDCF_tree");
            vRw.InitType(CxbDef.xb_DCF, CxbDef.xb_DCF);
            vRw.InitGrid(pHvdc);

            vRw.OnSave();
        }

        protected void doSave_xbDcLine()
        {

            CxbRwDcLine vRw = new CxbRwDcLine();

            vRw.InitAdo(RwAdo);
            vRw.InitTable("xbDcLine", "xbDcLine_tree", "xbDcLine_tree");
            vRw.InitType(CxbDef.xb_DCLine, CxbDef.xb_DCLine);
            vRw.InitGrid(pHvdc);

            vRw.OnSave();
        }

        protected void doSave_xbGroundLine()
        {

            CxbRwGroundLine vRw = new CxbRwGroundLine();

            vRw.InitAdo(RwAdo);
            vRw.InitTable("xbGroundLine", "xbGroundLine_tree", "xbGroundLine_tree");
            vRw.InitType(CxbDef.xb_GroundLine, CxbDef.xb_GroundLine);
            vRw.InitGrid(pHvdc);

            vRw.OnSave();
        }

        protected void doSave_xbGround()
        {

            CxbRwShunt vRw = new CxbRwShunt();

            vRw.InitAdo(RwAdo);
            vRw.InitTable("xbGround");
            vRw.InitType(CxbDef.xb_Ground, CxbDef.xb_Ground);
            vRw.InitGrid(pHvdc);

            vRw.OnSave();
        }

        protected void doSave_xbXfC()
        {

            CxbRwShunt vRw = new CxbRwShunt();

            vRw.InitAdo(RwAdo);
            vRw.InitTable("xbXf_C");
            vRw.InitType(CxbDef.xb_XfC, CxbDef.xb_XfC);
            vRw.InitGrid(pHvdc);

            vRw.OnSave();
        }

        protected void doSave_xbCoupleC()
        {

            CxbRwShunt vRw = new CxbRwShunt();

            vRw.InitAdo(RwAdo);
            vRw.InitTable("xbCouple_C");
            vRw.InitType(CxbDef.xb_CoupleC, CxbDef.xb_CoupleC);
            vRw.InitGrid(pHvdc);

            vRw.OnSave();
        }

        protected void doSave_xbPulseC()
        {

            CxbRwShunt vRw = new CxbRwShunt();

            vRw.InitAdo(RwAdo);
            vRw.InitTable("xbPulse_C");
            vRw.InitType(CxbDef.xb_PulseC, CxbDef.xb_PulseC);
            vRw.InitGrid(pHvdc);

            vRw.OnSave();
        }

        protected void doSave_xbShunt()
        {

            CxbRwShunt vRw = new CxbRwShunt();

            vRw.InitAdo(RwAdo);
            vRw.InitTable("xbShunt");
            vRw.InitType(CxbDef.xb_Shunt, CxbDef.xb_Shunt);
            vRw.InitGrid(pHvdc);

            vRw.OnSave();
        }

        protected void doSave_xbBranch()
        {

            CxbRwBranch vRw = new CxbRwBranch();

            vRw.InitAdo(RwAdo);
            vRw.InitTable("xbBranch");
            vRw.InitType(CxbDef.xb_Branch, CxbDef.xb_Branch);
            vRw.InitGrid(pHvdc);

            vRw.OnSave();
        }

        protected void doSave_xbMonitor()
        {

            CxbRwRLCs vRw = new CxbRwRLCs();

            vRw.InitAdo(RwAdo);
            vRw.InitTable("xbMonitor", "xbMonitor_tree", "xbMonitor_tree");
            vRw.InitType(CxbDef.xb_Monitor, CxbDef.xb_Monitor);
            vRw.InitGrid(pHvdc);

            vRw.OnSave();
        }

        protected void doSave_xbTrap()
        {

            CxbRwRLCs vRw = new CxbRwRLCs();

            vRw.InitAdo(RwAdo);
            vRw.InitTable("xbTrap", "xbTrap_tree", "xbTrap_tree");
            vRw.InitType(CxbDef.xb_Trap, CxbDef.xb_Trap);
            vRw.InitGrid(pHvdc);

            vRw.OnSave();
        }
    }
}