///////////////////////////////////////////////////////////
//  CMyParams.cs
//  Implementation of the Class CMyParams
//  Generated by Enterprise Architect
//  Created on:      09-5ÔÂ-2017 16:15:35
//  Original author: open2
///////////////////////////////////////////////////////////

using System.Windows.Forms;

namespace Yao.BaseFrame.App
{
    public static class CMyParams
    {        
        public static int ProjectID;
        public static string ProjectName;

        public static string ExeFilePath;

        public static string PRJFilePath;
        public static string PRJFile;

        public static string dbfPath;

        public static void Init()
        {
            ProjectID = 1;
            ProjectName = "ProjectName";

            ExeFilePath = Application.StartupPath + "\\";

            PRJFilePath = ExeFilePath;

            PRJFile = PRJFilePath+"Hvdc-MT.accdb";

        }


        public static void Clear()
        {

        }

        public static void Release()
        {

        }

    }//end CMyParams

}//end namespace BaseFrame