///////////////////////////////////////////////////////////
//  C3pDevXf2.cs
//  Implementation of the Class C3pDevXf2
//  Generated by Enterprise Architect
//  Created on:      09-5月-2017 17:08:08
//  Original author: open2
///////////////////////////////////////////////////////////


namespace Hvdc.MT.U3p.Device
{
    /// <summary>
    /// 主回路换流变压器
    /// </summary>
    public class C3pDevXf2 : C3pDevTwoDot
    {
        /**
* 变压器额定容量
*/
        public double SN;
        /**
        * 网侧额定交流电压
        */
        public double UacN;
        /**
        * 阀侧额定交流电压
        */
        public double UvN;
        /**
        * 短路阻抗百分比
        */
        public double Ukp;
        /**
        * 阻性压降百分比
        */
        public double Urp;
        /**
        * 额定变比
        */
        public double TkN;
        /**
        * 额定变比偏差
        */
        public double dTkN;
        /**
        * 变压器正序阀侧滞后网侧角度
        */
        public double PhaseShift;
        /**
        * 变压器等效电感电感标准差
        */
        public double Std_Lt;
        /**
        * 偏差程序分配模式变压器等效电感偏差
        */
        public double Dis_dLt;
        /**
        * 变压器等效电感A相偏差
        */
        public double dLtA;
        /**
        * 变压器等效电感B相偏差
        */
        public double dLtB;
        /**
        * 变压器等效电感B相偏差
        */
        public double dLtC;

    }//end C3pDevXf2

}//end namespace mcDev