///////////////////////////////////////////////////////////
//  CmcDevConvertor.cs
//  Implementation of the Class CmcDevConvertor
//  Generated by Enterprise Architect
//  Created on:      09-5月-2017 17:08:08
//  Original author: open2
///////////////////////////////////////////////////////////




namespace Hvdc.MT.mc.Device
{
    /// <summary>
    /// 换流器
    /// </summary>
    public class CmcDevConvertor : CmcDevTwoDot
    {

        /// <summary>
        /// 换流器有功额定值
        /// </summary>
        protected double f_PconvN;
        /// <summary>
        /// 换流器无功额定值
        /// </summary>
        protected double f_QconvN;
        /// <summary>
        /// 换相角额定值(度)
        /// </summary>
        protected double f_miuN;
        /// <summary>
        /// 额定触发角/关断角
        /// </summary>
        protected double f_Alpha_gamaN;
        /// <summary>
        /// 触发角/关断角最大值
        /// </summary>
        protected double f_AngleMax;
        /// <summary>
        /// 触发角/关断角最小值
        /// </summary>
        protected double f_AngleMin;
        /// <summary>
        /// 额定直流功率
        /// </summary>
        protected double f_PdN;
        /// <summary>
        /// 额定直流电压
        /// </summary>
        protected double f_UdN;
        /// <summary>
        /// 6脉动正向导通压降
        /// </summary>
        protected double f_UT;
        /// <summary>
        /// 每极12脉动换流组数
        /// </summary>
        protected int f_Valvor12Count;
        protected double f_UdioN;
        /// <summary>
        /// 阀侧额定电压
        /// </summary>
        protected double f_UvN;
        /// <summary>
        /// 直流电流,，计算得出
        /// </summary>
        protected double f_IdN;
        /// <summary>
        /// 换流器类型（整流逆变）
        /// </summary>
        protected int f_StationType;
        /// <summary>
        /// 换流器控制类型（定电流，定功率，定电压）
        /// </summary>
        protected int f_StationCtrlType;
        /// <summary>
        /// 换流器控制类型额定值
        /// </summary>
        protected int f_StationCtrlTypeN;
        /// <summary>
        /// 是否单极金属回线时接地
        /// </summary>
        protected int f_IsGround;
        /// <summary>
        /// 角度参考值
        /// </summary>
        protected double f_AngleRef;
        /// <summary>
        /// 电气量测量换流站
        /// </summary>
        protected string f_MeasureStation;

        public double PconvN
        {
            get
            {
                return f_PconvN;
            }
            set
            {
                f_PconvN = value;
            }
        }

        public double QconvN
        {
            get
            {
                return f_QconvN;
            }
            set
            {
                f_QconvN = value;
            }
        }

        public double miuN
        {
            get
            {
                return f_miuN;
            }
            set
            {
                f_miuN = value;
            }
        }

        /// <summary>
        /// 额定触发角/关断角
        /// </summary>
        public double Alpha_gamaN
        {
            get
            {
                return f_Alpha_gamaN;
            }
            set
            {
                f_Alpha_gamaN = value;
            }
        }

        /// <summary>
        /// 触发角/关断角最大值
        /// </summary>
        public double AngleMax
        {
            get
            {
                return f_AngleMax;
            }
            set
            {
                f_AngleMax = value;
            }
        }

        /// <summary>
        /// 触发角/关断角最小值
        /// </summary>
        public double AngleMin
        {
            get
            {
                return f_AngleMin;
            }
            set
            {
                f_AngleMin = value;
            }
        }

        /// <summary>
        /// 额定直流功率
        /// </summary>
        public double PdN
        {
            get
            {
                return f_PdN;
            }
            set
            {
                f_PdN = value;
            }
        }

        /// <summary>
        /// 额定直流电压
        /// </summary>
        public double UdN
        {
            get
            {
                return f_UdN;
            }
            set
            {
                f_UdN = value;
            }
        }

        /// <summary>
        /// 6脉动正向导通压降
        /// </summary>
        public double UT
        {
            get
            {
                return f_UT;
            }
            set
            {
                f_UT = value;
            }
        }

        /// <summary>
        /// 每极12脉动换流组数
        /// </summary>
        public int Valvor12Count
        {
            get
            {
                return f_Valvor12Count;
            }
            set
            {
                f_Valvor12Count = value;
            }
        }

        public double UdioN
        {
            get
            {
                return f_UdioN;
            }
            set
            {
                f_UdioN = value;
            }
        }

        /// <summary>
        /// 阀侧额定电压
        /// </summary>
        public double UvN
        {
            get
            {
                return f_UvN;
            }
            set
            {
                f_UvN = value;
            }
        }

        /// <summary>
        /// 直流电流,，计算得出
        /// </summary>
        public double IdN
        {
            get
            {
                return f_IdN;
            }
            set
            {
                f_IdN = value;
            }
        }

        /// <summary>
        /// 换流器类型（整流逆变）
        /// </summary>
        public int StationType
        {
            get
            {
                return f_StationType;
            }
            set
            {
                f_StationType = value;
            }
        }

        /// <summary>
        /// 换流器控制类型（定电流，定功率，定电压）
        /// </summary>
        public int StationCtrlType
        {
            get
            {
                return f_StationCtrlType;
            }
            set
            {
                f_StationCtrlType = value;
            }
        }

        /// <summary>
        /// 电气量测量换流站
        /// </summary>
        public string MeasureStation
        {
            get
            {
                return f_MeasureStation;
            }
            set
            {
                f_MeasureStation = value;
            }
        }

        /// <summary>
        /// 角度参考值
        /// </summary>
        public double AngleRef
        {
            get
            {
                return f_AngleRef;
            }
            set
            {
                f_AngleRef = value;
            }
        }

        /// <summary>
        /// 是否单极金属回线时接地
        /// </summary>
        public int IsGround
        {
            get
            {
                return f_IsGround;
            }
            set
            {
                f_IsGround = value;
            }
        }

        /// <summary>
        /// 换流器控制类型额定值
        /// </summary>
        public int StationCtrlTypeN
        {
            get
            {
                return f_StationCtrlTypeN;
            }
            set
            {
                f_StationCtrlTypeN = value;
            }
        }

    }//end CmcDevConvertor

}//end namespace mcDev