///////////////////////////////////////////////////////////
//  CmcDevXf2.cs
//  Implementation of the Class CmcDevXf2
//  Generated by Enterprise Architect
//  Created on:      09-5月-2017 17:08:08
//  Original author: open2
///////////////////////////////////////////////////////////


namespace Hvdc.MT.mc.Device
{
    /// <summary>
    /// 主回路换流变压器
    /// </summary>
    public class CmcDevXf2 : CmcDevTwoDot
    {
        /// <summary>
        /// 定电压参考值
        /// </summary>
        protected double f_FixedURef;

        /// <summary>
        /// 定电压参考值
        /// </summary>
        protected double f_FixedUType;


        /// <summary>
        /// 触发角/关断角最大值
        /// </summary>
        protected double f_AngleMax;
        /// <summary>
        /// 触发角/关断角最小值
        /// </summary>
        protected double f_AngleMin;
       
        /// <summary>
        /// 分接头控制类型
        /// </summary>
        protected int f_TapCtrlType;
        /// <summary>
        /// 分接头最大档位
        /// </summary>
        protected int f_TapMax;
        /// <summary>
        /// 分接头最小档位
        /// </summary>
        protected int f_TapMin;
        /// <summary>
        /// 分接头额定档位
        /// </summary>
        protected int f_TapN;
        /// <summary>
        /// 分解头调整步长
        /// </summary>
        protected double f_TapSetup;
        /// <summary>
        /// 额定变比
        /// </summary>
        protected double f_TkN;
        /// <summary>
        /// 网侧额定交流电压
        /// </summary>
        protected double f_UacN;
        /// <summary>
        /// 短路阻抗百分比
        /// </summary>
        protected double f_Ukp;
        /// <summary>
        /// 阻性压降百分比
        /// </summary>
        protected double f_Urp;
        /// <summary>
        /// 阀侧最大交流电压
        /// </summary>
        protected double f_UvMax;
        /// <summary>
        /// 阀侧额定交流电压
        /// </summary>
        protected double f_UvN;

        /// <summary>
        /// 触发角/关断角最大值
        /// </summary>
        public double AngleMax
        {
            get
            {
                return f_AngleMax;
            }
            set
            {
                f_AngleMax = value;
            }
        }

        /// <summary>
        /// 触发角/关断角最小值
        /// </summary>
        public double AngleMin
        {
            get
            {
                return f_AngleMin;
            }
            set
            {
                f_AngleMin = value;
            }
        }

        /// <summary>
        /// 定电压参考值
        /// </summary>
        public double FixedURef
        {
            get
            {
                return f_FixedURef;
            }
            set
            {
                f_FixedURef = value;
            }
        }

        public double FixedUType
        {
            get
            {
                return f_FixedUType;
            }
            set
            {
                f_FixedUType = value;
            }
        }

        /// <summary>
        /// 分接头控制类型
        /// </summary>
        public int TapCtrlType
        {
            get
            {
                return f_TapCtrlType;
            }
            set
            {
                f_TapCtrlType = value;
            }
        }

        /// <summary>
        /// 分接头最大档位
        /// </summary>
        public int TapMax
        {
            get
            {
                return f_TapMax;
            }
            set
            {
                f_TapMax = value;
            }
        }

        /// <summary>
        /// 分接头最小档位
        /// </summary>
        public int TapMin
        {
            get
            {
                return f_TapMin;
            }
            set
            {
                f_TapMin = value;
            }
        }

        /// <summary>
        /// 分接头额定档位
        /// </summary>
        public int TapN
        {
            get
            {
                return f_TapN;
            }
            set
            {
                f_TapN = value;
            }
        }

        /// <summary>
        /// 分解头调整步长
        /// </summary>
        public double TapSetup
        {
            get
            {
                return f_TapSetup;
            }
            set
            {
                f_TapSetup = value;
            }
        }

        /// <summary>
        /// 额定变比
        /// </summary>
        public double TkN
        {
            get
            {
                return f_TkN;
            }
            set
            {
                f_TkN = value;
            }
        }

        /// <summary>
        /// 网侧额定交流电压
        /// </summary>
        public double UacN
        {
            get
            {
                return f_UacN;
            }
            set
            {
                f_UacN = value;
            }
        }

        /// <summary>
        /// 短路阻抗百分比
        /// </summary>
        public double Ukp
        {
            get
            {
                return f_Ukp;
            }
            set
            {
                f_Ukp = value;
            }
        }

        /// <summary>
        /// 阻性压降百分比
        /// </summary>
        public double Urp
        {
            get
            {
                return f_Urp;
            }
            set
            {
                f_Urp = value;
            }
        }

        /// <summary>
        /// 阀侧最大交流电压
        /// </summary>
        public double UvMax
        {
            get
            {
                return f_UvMax;
            }
            set
            {
                f_UvMax = value;
            }
        }

        /// <summary>
        /// 阀侧额定交流电压
        /// </summary>
        public double UvN
        {
            get
            {
                return f_UvN;
            }
            set
            {
                f_UvN = value;
            }
        }

    }//end CmcDevXf2

}//end namespace mcDev