///////////////////////////////////////////////////////////
//  CmcDevGround.cs
//  Implementation of the Class CmcDevGround
//  Generated by Enterprise Architect
//  Created on:      09-5ÔÂ-2017 17:08:08
//  Original author: open2
///////////////////////////////////////////////////////////




namespace Hvdc.MT.mc.Device
{
    public class CmcDevGround : CmcDevShunt
    {

    }//end CmcDevGround

}//end namespace mcDev