///////////////////////////////////////////////////////////
//  CmcDevAcSys.cs
//  Implementation of the Class CmcDevAcSys
//  Generated by Enterprise Architect
//  Created on:      09-5月-2017 17:08:07
//  Original author: open2
///////////////////////////////////////////////////////////



namespace Hvdc.MT.mc.Device
{
    /// <summary>
    /// 主回路 交流系统
    /// </summary>
    public class CmcDevAcSys : CmcDevOneDot
    {

        protected double f_QfMinN;
        protected double f_QfMaxN;
        /// <summary>
        /// 交流系统吸收最大无功
        /// </summary>
        protected double f_QinMax;
        /// <summary>
        /// 交流系统发出最大无功
        /// </summary>
        protected double f_QoutMax;
        /// <summary>
        /// 交流电压极小值
        /// </summary>
        protected double f_UacExMin;
        /// <summary>
        /// 交流电压最大值
        /// </summary>
        protected double f_UacMax;
        /// <summary>
        /// 交流电压最小值
        /// </summary>
        protected double f_UacMin;
        /// <summary>
        /// 交流侧额定线电压
        /// </summary>
        protected double f_UacN;

        public double QfMinN
        {
            get
            {
                return f_QfMinN;
            }
            set
            {
                f_QfMinN = value;
            }
        }

        public double QfMaxN
        {
            get
            {
                return f_QfMaxN;
            }
            set
            {
                f_QfMaxN = value;
            }
        }

        /// <summary>
        /// 交流系统吸收最大无功
        /// </summary>
        public double QinMax
        {
            get
            {
                return f_QinMax;
            }
            set
            {
                f_QinMax = value;
            }
        }

        /// <summary>
        /// 交流系统发出最大无功
        /// </summary>
        public double QoutMax
        {
            get
            {
                return f_QoutMax;
            }
            set
            {
                f_QoutMax = value;
            }
        }

        /// <summary>
        /// 交流电压极小值
        /// </summary>
        public double UacExMin
        {
            get
            {
                return f_UacExMin;
            }
            set
            {
                f_UacExMin = value;
            }
        }

        /// <summary>
        /// 交流电压最大值
        /// </summary>
        public double UacMax
        {
            get
            {
                return f_UacMax;
            }
            set
            {
                f_UacMax = value;
            }
        }

        /// <summary>
        /// 交流电压最小值
        /// </summary>
        public double UacMin
        {
            get
            {
                return f_UacMin;
            }
            set
            {
                f_UacMin = value;
            }
        }

        /// <summary>
        /// 交流侧额定线电压
        /// </summary>
        public double UacN
        {
            get
            {
                return f_UacN;
            }
            set
            {
                f_UacN = value;
            }
        }

    }//end CmcDevAcSys

}//end namespace mcDev