///////////////////////////////////////////////////////////
//  CmcRwConvertor.cs
//  Implementation of the class CmcRwConvertor
//  Generated by Enterprise Architect
//  Created on:      09-5ÔÂ-2017 8:08:04
//  Original author: open2
///////////////////////////////////////////////////////////


using Hvdc.MT.mc.Device;
using Yao.BaseFrame.Device;
using Yao.BaseFrame.Func;

namespace Hvdc.MT.mc.Rw
{
    public class CmcRwConvertor : CmcRwTwo
    {
        protected override void doLoad(CDevBase vDevice)
        {
            CmcDevConvertor vDev;
            vDev = (CmcDevConvertor)vDevice;

            base.doLoad(vDevice);

            vDev.Valvor12Count = RwAdo.ReadInt32("Valvor12Count") ;

            vDev.PconvN = RwAdo.ReadDouble("PconvN") ;
            vDev.QconvN = RwAdo.ReadDouble("QconvN") ;

            vDev.miuN = RwAdo.ReadDouble("miuN") ;
            vDev.Alpha_gamaN = RwAdo.ReadDouble("Alpha_gamaN") ;

            vDev.AngleMax = RwAdo.ReadDouble("AngleMax") ;
            vDev.AngleMin = RwAdo.ReadDouble("AngleMin") ;

            vDev.PdN = RwAdo.ReadDouble("PdN") ;
            vDev.UdN = RwAdo.ReadDouble("UdN") ;
            vDev.IdN = RwAdo.ReadDouble("IdN") ;

            vDev.UT = RwAdo.ReadDouble("UT") ;
            vDev.UdioN = RwAdo.ReadDouble("UdioN") ;
            vDev.UvN = RwAdo.ReadDouble("UvN") ;

            vDev.StationType = RwAdo.ReadInt32("StationType") ;
            vDev.StationCtrlType = RwAdo.ReadInt32("StationCtrlType") ;
            vDev.StationCtrlTypeN = RwAdo.ReadInt32("StationCtrlTypeN") ;

            vDev.IsGround = RwAdo.ReadInt32("IsGround") ;

            vDev.AngleRef = RwAdo.ReadDouble("AngleRef") ;
            vDev.MeasureStation =RwAdo.ReadString("MeasureStation");

        }

        /// 
        /// <param name="vDevice"></param>
        protected override void doSave(CDevBase vDevice)
        {
            CmcDevConvertor vDev;
            vDev = (CmcDevConvertor)vDevice;

            base.doSave(vDevice);

            SqlStr = SqlStr + ",";
            SqlParam = SqlParam + ",";

            SqlStr = SqlStr + "Valvor12Count,";
            SqlParam = SqlParam + GetString(vDev.Valvor12Count) + ",";

            SqlStr = SqlStr + "PconvN, ";
            SqlParam = SqlParam + GetString(vDev.PconvN) + ",";

            SqlStr = SqlStr + "QconvN, ";
            SqlParam = SqlParam + GetString(vDev.QconvN) + ",";

            SqlStr = SqlStr + "miuN, ";
            SqlParam = SqlParam + GetString(vDev.miuN) + ",";

            SqlStr = SqlStr + "Alpha_gamaN, ";
            SqlParam = SqlParam + GetString(vDev.Alpha_gamaN) + ",";

            SqlStr = SqlStr + "AngleMax, ";
            SqlParam = SqlParam + GetString(vDev.AngleMax) + ",";

            SqlStr = SqlStr + "AngleMin, ";
            SqlParam = SqlParam + GetString(vDev.AngleMin) + ",";

            SqlStr = SqlStr + "PdN, ";
            SqlParam = SqlParam + GetString(vDev.PdN) + ",";

            SqlStr = SqlStr + "UdN, ";
            SqlParam = SqlParam + GetString(vDev.UdN) + ",";

            SqlStr = SqlStr + "IdN, ";
            SqlParam = SqlParam + GetString(vDev.IdN) + ",";

            SqlStr = SqlStr + "UT, ";
            SqlParam = SqlParam + GetString(vDev.UT) + ",";

            SqlStr = SqlStr + "UdioN, ";
            SqlParam = SqlParam + GetString(vDev.UdioN) + ",";

            SqlStr = SqlStr + "UvN, ";
            SqlParam = SqlParam + GetString(vDev.UvN) + ",";

            SqlStr = SqlStr + "StationType, ";
            SqlParam = SqlParam + GetString(vDev.StationType) + ",";

            SqlStr = SqlStr + "StationCtrlType, ";
            SqlParam = SqlParam + GetString(vDev.StationCtrlType) + ",";

            SqlStr = SqlStr + "StationCtrlTypeN, ";
            SqlParam = SqlParam + GetString(vDev.StationCtrlTypeN) + ",";

            SqlStr = SqlStr + "IsGround, ";
            SqlParam = SqlParam + GetString(vDev.IsGround) + ",";

            SqlStr = SqlStr + "AngleRef, ";
            SqlParam = SqlParam + GetString(vDev.AngleRef) + ",";

            SqlStr = SqlStr + "MeasureStation ";
            SqlParam = SqlParam + GetString(vDev.MeasureStation) ;

        }

    }//end CmcRwConvertor

}//end namespace mc