///////////////////////////////////////////////////////////
//  CmcRwDcLine.cs
//  Implementation of the class CmcRwDcLine
//  Generated by Enterprise Architect
//  Created on:      10-5ÔÂ-2017 16:02:15
//  Original author: open2
///////////////////////////////////////////////////////////


using Hvdc.MT.mc.Device;
using Yao.BaseFrame.Device;
using Yao.BaseFrame.Func;

namespace Hvdc.MT.mc.Rw
{
    public class CmcRwDcLine : CmcRwTwo
    {
        protected override void doLoad(CDevBase vDevice)
        {
            CmcDevDcLine vDev;
            vDev = (CmcDevDcLine)vDevice;

            base.doLoad(vDevice);

            vDev.ZrN = RwAdo.ReadDouble("ZrN") ;
            vDev.ZrMax = RwAdo.ReadDouble("ZrMax") ;
            vDev.ZrMin = RwAdo.ReadDouble("ZrMin") ;            
        }

        /// 
        /// <param name="vDevice"></param>
        protected override void doSave(CDevBase vDevice)
        {
            CmcDevDcLine vDev;
            vDev = (CmcDevDcLine)vDevice;

            base.doSave(vDevice);

            SqlStr = SqlStr + ",";
            SqlParam = SqlParam + ",";

            SqlStr = SqlStr + "ZrN, ";
            SqlParam = SqlParam + GetString(vDev.ZrN) + ",";

            SqlStr = SqlStr + "ZrMax, ";
            SqlParam = SqlParam + GetString(vDev.ZrMax) + ",";

            SqlStr = SqlStr + "ZrMin ";
            SqlParam = SqlParam + GetString(vDev.ZrMin);

        }

    }//end CmcRwDcLine

}//end namespace mc