///////////////////////////////////////////////////////////
//  CmcRwMetalLine.cs
//  Implementation of the class CmcRwMetalLine
//  Generated by Enterprise Architect
//  Created on:      10-5ÔÂ-2017 16:00:33
//  Original author: open2
///////////////////////////////////////////////////////////


using Hvdc.MT.mc.dataRw;
using Hvdc.MT.mc.Device;

namespace Hvdc.MT.mc.Rw
{
    public class CmcDataRwMetalLine : CmcDataRwDcLine
    {

    }//end CmcRwMetalLine

}//end namespace mc
