///////////////////////////////////////////////////////////
//  CmcRw.cs
//  Implementation of the class CmcRw
//  Generated by Enterprise Architect
//  Created on:      09-5月-2017 8:08:04
//  Original author: open2
///////////////////////////////////////////////////////////

using Yao.BaseFrame.dataRw;
using Yao.BaseFrame.DevTBL;

using Hvdc.MT.mc.Device;
using Hvdc.MT.mc.DevTBL;
using Yao.BaseFrame.Func;
using System.Data;
using Yao.BaseFrame.Device;

namespace Hvdc.MT.mc.dataRw
{
    /// <summary>
    /// 主回路计算读写
    /// </summary>
    public class CmcDataRwDev : CDataRwDev
    {
    }

}//end namespace mc