///////////////////////////////////////////////////////////
//  C3pRw.cs
//  Implementation of the class C3pRw
//  Generated by Enterprise Architect
//  Created on:      09-5月-2017 8:08:04
//  Original author: open2
///////////////////////////////////////////////////////////

using Yao.BaseFrame.Rw;

namespace Hvdc.MT.U3p.Rw
{
    /// <summary>
    /// 主回路计算读写
    /// </summary>
    public class C3pRw : CRwDev
    {
    }//end C3pRw

}//end namespace mc