///////////////////////////////////////////////////////////
//  CMyMvcs.cs
//  Implementation of the Class CMyMvcs
//  Generated by Enterprise Architect
//  Created on:      09-5ÔÂ-2017 16:15:35
//  Original author: open2
///////////////////////////////////////////////////////////

using Yao.BaseFrame.Rw;

namespace Yao.BaseFrame.App
{
    public static class CMyMvcs
    {
        public static void Release()
        {

        }

        public static void Clear()
        {

        }

        public static void Init()
        {

        }

        public static void OnLoad()
        {

        }

        public static void OnSave()
        {

        }

    }//end CMyMvcs

}//end namespace BaseFrame