///////////////////////////////////////////////////////////
//  C3pDevBase.cs
//  Implementation of the Class C3pDevBase
//  Generated by Enterprise Architect
//  Created on:      09-5ÔÂ-2017 17:08:08
//  Original author: open2
///////////////////////////////////////////////////////////


using Yao.BaseFrame.Device;

namespace Hvdc.MT.U3p.Device
{
    public class C3pDevBase : CDevBase
    {

    }//end C3pDevBase

}//end namespace mcDev