///////////////////////////////////////////////////////////
//  CmcDevTwoDot.cs
//  Implementation of the Class CmcDevTwoDot
//  Generated by Enterprise Architect
//  Created on:      09-5月-2017 17:08:08
//  Original author: open2
///////////////////////////////////////////////////////////




namespace Hvdc.MT.mc.Device
{
    /// <summary>
    /// 双端点设备
    /// </summary>
    public class CmcDevTwoDot : CmcDevBase
    {
        public CmcDevTwoDot()
        {
            StaCount = 1;
            dotCount = 2;
        }

    }//end CmcDevTwoDot

}//end namespace mcDev