///////////////////////////////////////////////////////////
//  CmcDevMetalLine.cs
//  Implementation of the Class CmcDevMetalLine
//  Generated by Enterprise Architect
//  Created on:      09-5ÔÂ-2017 17:08:08
//  Original author: open2
///////////////////////////////////////////////////////////




namespace Hvdc.MT.mc.Device
{
    public class CmcDevMetalLine : CmcDevDcLine
    {

    }//end CmcDevMetalLine

}//end namespace mcDev