///////////////////////////////////////////////////////////
//  CMyFunc.cs
//  Implementation of the Class CMyFunc
//  Generated by Enterprise Architect
//  Created on:      09-5月-2017 16:15:35
//  Original author: open2
///////////////////////////////////////////////////////////

//using System.Guid;

namespace Yao.BaseFrame.Func
{
    public static class CMyFunc
    {
        public static string ExtractFilePath(string vFileNameNoDir,string vFileName)
        {
            //string fileNameNotDir = fileDialog.SafeFileName; // 文件目录不包含路劲
            //int dbNameIndex = fileDialog.FileName.LastIndexOf(fileNameNotDir);
            //string dbDir = fileDialog.FileName.Remove(dbNameIndex);

            int vIndex = vFileName.IndexOf(vFileNameNoDir);
            string vFilePath= vFileName.Remove(vIndex);

            return vFilePath;

        }
    
        public static string CreateObjID()
        {
            //Guid.NewGuid().ToString();

            /*
            unsigned x;
            unsigned vSeed;
            //return 0;

            vSeed = (unsigned)time(NULL);
            srand(vSeed); //srand(3)
            x = rand();

            //x = x / RAND_MAX;

            return to_string(x);
            */

            return "Guid";
        }

        public static string GetString(string vStr)
        {
            vStr = "'" + vStr + "'";

            return vStr;
        }

        public static string GetString(double vX)
        {
            string vStr;

            vStr = vX.ToString();

            return vStr;
        }

        public static string GetString(int vX)
        {
            string vStr;

            vStr = vX.ToString();

            return vStr;
        }

    }//end CMyFunc

}//end namespace BaseFrame