///////////////////////////////////////////////////////////
//  CHvdcMvcs.cs
//  Implementation of the Class CHvdcMvcs
//  Generated by Enterprise Architect
//  Created on:      09-5ÔÂ-2017 16:15:35
//  Original author: open2
///////////////////////////////////////////////////////////


using Hvdc.MT.xb.dataRw;
using Hvdc.MT.xb.Rw;
using Hvdc.MT.xb.RwMvc;
using System.Data;
using Yao.BaseFrame.Device;

namespace Hvdc.MT.xb.App
{
    public static class CxbMvcs
    {
        public static CxbRwMvc pxbRwMvc;

        public static void Release()
        {
            
        }

        public static void Clear()
        {

        }

        public static void Init()
        {           
            pxbRwMvc = new CxbRwMvc();
            pxbRwMvc.InitGrid(CxbVars.pxbHvdcGrid);
        }

        public static void OnLoad()
        {
            pxbRwMvc.InitAdo(CxbParams.dbfFile);
            pxbRwMvc.OnLoad(CxbParams.dbfFile);

            //
            CxbVars.pxbHvdcGrid.AddToStation();
        }

        public static void OnSave()
        {
            pxbRwMvc.InitAdo(CxbParams.dbfFile);
            pxbRwMvc.OnSave(CxbParams.dbfFile);
        }
        public static void OnLoad(string vdbf)
        {
            pxbRwMvc.InitAdo(vdbf);
            pxbRwMvc.OnLoad(vdbf);

            //
            CxbVars.pxbHvdcGrid.AddToStation();
        }

        public static void OnSave(string vdbf)
        {
            pxbRwMvc.InitAdo(vdbf);
            pxbRwMvc.OnSave(vdbf);
        }

        public static void OnLoad(int vtblType)
        {
            pxbRwMvc.InitAdo(CxbParams.dbfFile);
            pxbRwMvc.OnLoad(vtblType);
            //
            CxbVars.pxbHvdcGrid.AddToStation();
        }

        public static void OnSave(int vtblType)
        {
            pxbRwMvc.InitAdo(CxbParams.dbfFile);
            pxbRwMvc.OnSave(vtblType);
        }

        public static void OnLoad(int vtblType, string vDevicName)
        {
            pxbRwMvc.InitAdo(CxbParams.dbfFile);
            pxbRwMvc.OnLoad(vtblType, vDevicName);
        }

        public static void OnSave(int vtblType, CDevBase vDev)
        {
            pxbRwMvc.InitAdo(CxbParams.dbfFile);
            pxbRwMvc.OnSave(vtblType, vDev);
        }

        public static void xbOnLoadOrder()
        {
            CxbRwOrderMvc vRwMvc;

            vRwMvc = new CxbRwOrderMvc();

            vRwMvc.InitAdo(CxbParams.dbfFile);
            vRwMvc.InitOrder(CxbVars.pxbOrder);
            vRwMvc.OnLoad(CxbParams.dbfFile);

        }

        public static void xbOnSaveOrder()
        {
            CxbRwOrderMvc vRwMvc;

            vRwMvc = new CxbRwOrderMvc();

            vRwMvc.InitAdo(CxbParams.dbfFile);
            vRwMvc.InitOrder(CxbVars.pxbOrder);
            vRwMvc.OnSave(CxbParams.dbfFile);

        }

        public static void zkOnLoadOrder()
        {
            CzkRwOrderMvc vRwMvc;

            vRwMvc = new CzkRwOrderMvc();

            vRwMvc.InitAdo(CxbParams.dbfFile);
            vRwMvc.InitOrder(CxbVars.pzkOrder);
            vRwMvc.OnLoad(CxbParams.dbfFile);

        }

        public static void zkOnSaveOrder()
        {
            CzkRwOrderMvc vRwMvc;

            vRwMvc = new CzkRwOrderMvc();

            vRwMvc.InitAdo(CxbParams.dbfFile);
            vRwMvc.InitOrder(CxbVars.pzkOrder);
            vRwMvc.OnSave(CxbParams.dbfFile);

        }

        public static DataTable LoadResultFromMcResult(string vdbf)
        {

            CxbDataRwOrderMvc vRwMvc = new CxbDataRwOrderMvc();

            vRwMvc.InitAdo(vdbf);
            vRwMvc.InitOrder(CxbVars.pxbOrder);

            return vRwMvc.OnLoadTable();

        }


    }//end CxbMvcs

}//end namespace BaseFrame