///////////////////////////////////////////////////////////
//  CxbVars.cs
//  Implementation of the Class CxbVars
//  Generated by Enterprise Architect
//  Created on:      09-5ÔÂ-2017 16:38:39
//  Original author: open2
///////////////////////////////////////////////////////////

using Hvdc.MT.xb.DevTBL;
using Hvdc.MT.xb.Solve;

namespace Hvdc.MT.xb.App
{
    public static class CxbVars
    {
        public static CxbHvdcGrid pxbHvdcGrid;

        public static CxbOrder pxbOrder;
        public static CzkOrder pzkOrder;


        public static void Init()
        {
            pxbHvdcGrid = new CxbHvdcGrid();

            pxbOrder = new CxbOrder();
            pzkOrder = new CzkOrder();

        }
        public static void Release()
        {
            //pxbHvdcGrid.Release();
        }

        public static void Clear()
        {
           pxbHvdcGrid.Clear();


        }



    }//end CxbVars


}//end namespace xb