///////////////////////////////////////////////////////////
//  CxbParams.cs
//  Implementation of the Class CxbParams
//  Generated by Enterprise Architect
//  Created on:      09-5ÔÂ-2017 16:15:35
//  Original author: open2
///////////////////////////////////////////////////////////

using Yao.BaseFrame.App;

namespace Hvdc.MT.xb.App
{
    public static class CxbParams
    {
        public static string dbfFile {  get;set;}

        public static int xbStationCount { set; get; }

        public static void Clear()
        {            
        }
        public static void Init()
        {           
            xbStationCount = 2;
            //
            dbfFile = "..\\..\\..\\..\\DBF\\xbDBF.accdb";
        }
    }//end CxbParams

}//end namespace xb