///////////////////////////////////////////////////////////
//  CmcRwShunt.cs
//  Implementation of the class CmcRwShunt
//  Generated by Enterprise Architect
//  Created on:      09-5ÔÂ-2017 8:08:05
//  Original author: open2
///////////////////////////////////////////////////////////


using Hvdc.MT.mc.dataRw;
using Hvdc.MT.mc.Device;
using Yao.BaseFrame.Device;

namespace Hvdc.MT.mc.Rw
{
    public class CmcDataRwShunt : CmcDataRwOne
    {
        protected override void doLoad(CDevBase vDevice)
        {
            CmcDevOneDot vDev;
            vDev = (CmcDevOneDot)vDevice;

            base.doLoad(vDevice);

            /*
            vDev.Zr = RwAdo.ReadDouble("Zr") ;

            
            vDev.Z_L = RwAdo.ReadDouble("Z_L") ;
            vDev.Z_C = RwAdo.ReadDouble("Z_C") ;
            vDev.Zx_L = RwAdo.ReadDouble("Zx_L") ;
            vDev.Zx_C = RwAdo.ReadDouble("Zx_C") ;
            */

        }

        /// 
        /// <param name="vDevice"></param>
        protected override void doSave(CDevBase vDevice)
        {
            CmcDevOneDot vDev;
            vDev = (CmcDevOneDot)vDevice;

            base.doSave(vDevice);

            /*
            RwAdo.SaveField("Zr",vDev.Zr) ;
             
            RwAdo.SaveField("Z_L",vDev.Z_L) ;
            RwAdo.SaveField("Z_C",vDev.Z_C) ;

            RwAdo.SaveField("Zx_L",vDev.Zx_L) ;
            RwAdo.SaveField("Zx_C",vDev.Zx_C) ;

            */

        }

    }//end CmcRwShunt
}//end namespace mc