///////////////////////////////////////////////////////////
//  CBasicVo.cs
//  Implementation of the Class CBasicVo
//  Generated by Enterprise Architect
//  Created on:      11-5月-2017 18:55:17
//  Original author: open2
///////////////////////////////////////////////////////////

namespace Yao.BaseFrame.Device
{
    public class CBasicVo
    {

        /// <summary>
        /// 主键，唯一标识
        /// </summary>
        public int ID
        {
            set; get;
        }

        /// <summary>
        /// 工程标识
        /// </summary>
        public int ProjectID
        {
            set; get;
        }

        /// <summary>
        /// 定义实体所属类型如：主回路交流系统
        /// </summary>
        public string Type
        {
            get;
        }

        /// 
        /// <param name="vo"></param>
        public bool Equals(CBasicVo vo)
        {

            return vo != null && this.ID == vo.ID;
        }

        /// <summary>
        /// 是否同一类型下同一对象
        /// </summary>
        /// <param name="vo"></param>
        public bool EqualsSameType(CBasicVo vo)
        {

            return vo != null && this.ID == vo.ID && this.Type.Equals(vo.Type);
        }

    }//end CBasicVo

}//end namespace Device