///////////////////////////////////////////////////////////
//  CHvdcMvcs.cs
//  Implementation of the Class CHvdcMvcs
//  Generated by Enterprise Architect
//  Created on:      09-5ÔÂ-2017 16:15:35
//  Original author: open2
///////////////////////////////////////////////////////////


using Hvdc.MT.mc.Rw;
using Hvdc.MT.mc.RwMvc;
using Hvdc.MT.mc.dataRw;
using System.Data;
using Yao.BaseFrame.Device;

namespace Hvdc.MT.mc.App
{
    public static class CmcMvcs
    {
        public static CmcRwMvc pmcRwMvc;

        public static void Release()
        {
            
        }

        public static void Clear()
        {

        }

        public static void Init()
        {           
            pmcRwMvc = new CmcRwMvc();
            pmcRwMvc.InitGrid(CmcVars.pmcHvdcGrid);
        }


        public static void OnLoad()
        {
            pmcRwMvc.InitAdo(CmcParams.dbfFile);
            pmcRwMvc.OnLoad(CmcParams.dbfFile);

            //
            CmcVars.pmcHvdcGrid.AddToStation();
        }

        public static void OnSave()
        {
            pmcRwMvc.InitAdo(CmcParams.dbfFile);
            pmcRwMvc.OnSave(CmcParams.dbfFile);
        }

        public static void OnLoad(string vdbf)
        {
            pmcRwMvc.InitAdo(vdbf);
            pmcRwMvc.OnLoad(vdbf);

            //
            CmcVars.pmcHvdcGrid.AddToStation();
        }

        public static void OnSave(string vdbf)
        {
            pmcRwMvc.InitAdo(vdbf);
            pmcRwMvc.OnSave(vdbf);
        }

        public static void OnLoad(int vtblType)
        {
            pmcRwMvc.InitAdo(CmcParams.dbfFile);
            pmcRwMvc.OnLoad(vtblType);
            //
            CmcVars.pmcHvdcGrid.AddToStation();
        }

        public static void OnSave(int vtblType)
        {
            pmcRwMvc.InitAdo(CmcParams.dbfFile);
            pmcRwMvc.OnSave(vtblType);
        }

        public static void OnLoad(int vtblType,string vDevicName)
        {
            pmcRwMvc.InitAdo(CmcParams.dbfFile);
            pmcRwMvc.OnLoad(vtblType, vDevicName);
        }

        public static void OnSave(int vtblType,CDevBase vDev)
        {
            pmcRwMvc.InitAdo(CmcParams.dbfFile);
            pmcRwMvc.OnSave(vtblType, vDev);
        }


        public static void OnLoadOrder()
        {
            CmcRwOrderMvc vRwMvc;

            vRwMvc = new CmcRwOrderMvc();

            vRwMvc.InitAdo(CmcParams.dbfFile);
            vRwMvc.InitOrder(CmcVars.pOrder);
            vRwMvc.OnLoad(CmcParams.dbfFile);

        }

        public static void OnSaveOrder()
        {
            CmcRwOrderMvc vRwMvc;

            vRwMvc = new CmcRwOrderMvc();

            vRwMvc.InitAdo(CmcParams.dbfFile);
            vRwMvc.InitOrder(CmcVars.pOrder);
            vRwMvc.OnSave(CmcParams.dbfFile);
        }

        public static DataTable LoadCase_FromMC(string vCalName)
        {
            CmcVars.pResult.Clear();
            CmcVars.pResult.CalName=vCalName;


            CmcDataRwResultMvc vRwMvc = new CmcDataRwResultMvc();

            vRwMvc.InitAdo(CmcParams.dbfFile);
            vRwMvc.InitResult(CmcVars.pResult);

            return vRwMvc.OnLoadTable(vCalName);

        }


    }//end CHvdcMvcs

}//end namespace BaseFrame