///////////////////////////////////////////////////////////
//  CmcParams.cs
//  Implementation of the Class CmcParams
//  Generated by Enterprise Architect
//  Created on:      09-5ÔÂ-2017 16:15:35
//  Original author: open2
///////////////////////////////////////////////////////////

using Yao.BaseFrame.App;

namespace Hvdc.MT.mc.App
{
    public static class CmcParams
    {
        public static string dbfFile { get; set; }

        public static int mcStationCount { set; get; }
     
        public static void Clear()
        {
        }
       

        public static void Init()
        {
            mcStationCount = 2;

            //
            dbfFile = "..\\..\\..\\..\\DBF\\mcDBF.accdb";

        }
    }//end CmcParams

}//end namespace mc