///////////////////////////////////////////////////////////
//  CmcRwAcfilter.cs
//  Implementation of the class CmcRwAcfilter
//  Generated by Enterprise Architect
//  Created on:      09-5ÔÂ-2017 8:08:04
//  Original author: open2
///////////////////////////////////////////////////////////

using Hvdc.MT.mc.dataRw;
using Hvdc.MT.mc.Device;
using Yao.BaseFrame.Device;
using Yao.BaseFrame.Func;

namespace Hvdc.MT.mc.Rw
{
    public class CmcDataRwAcfilter : CmcDataRwOne
    {
        /// 
        /// <param name="vDevice"></param>
        protected override void doLoad(CDevBase vDevice)
        {
            CmcDevAcFilter vDev;
            vDev = (CmcDevAcFilter)vDevice;

            base.doLoad(vDevice);

            vDev.UacN = RwAdo.ReadDouble("UacN");
            vDev.QacN  =RwAdo.ReadDouble("QacN") ;
            vDev.QacfN = RwAdo.ReadDouble("QacfN") ;
          
        }

        /// 
        /// <param name="vDevice"></param>
        protected override void doSave(CDevBase vDevice)
        {
            CmcDevAcFilter vDev;
            vDev = (CmcDevAcFilter)vDevice;

            base.doSave(vDevice);

            RwAdo.SaveField("UacN", vDev.UacN);
            RwAdo.SaveField("QacN", vDev.QacN);
            RwAdo.SaveField("QacfN", vDev.QacfN);


        }

    }//end 

}//end namespace mc