///////////////////////////////////////////////////////////
//  CmcRw.cs
//  Implementation of the class CmcRw
//  Generated by Enterprise Architect
//  Created on:      09-5月-2017 8:08:04
//  Original author: open2
///////////////////////////////////////////////////////////



namespace Hvdc.MT.mc.dataRw
{
    /// <summary>
    /// 主回路计算读写
    /// </summary>
    public class CmcDataRwTwo : CmcDataRwDev
    {
    }//end CmcRw

}//end namespace mc