///////////////////////////////////////////////////////////
//  C3pDevTBL.cs
//  Implementation of the Class C3pDevTBL
//  Generated by Enterprise Architect
//  Created on:      09-5月-2017 17:08:08
//  Original author: open2
///////////////////////////////////////////////////////////

using Yao.BaseFrame.Device;
using Yao.BaseFrame.DevTBL;

using Hvdc.MT.U3p.Def;
using Hvdc.MT.U3p.Device;
using Hvdc.MT.U3p.Func;

namespace Hvdc.MT.U3p.DevTBL
{
    /// <summary>
    /// 主回路直流设备表
    /// </summary>
    public class C3pDevTBL : CDevTBL
    {
        /// 
        /// <param name="vDevType"></param>
        protected override CDevBase doNewDevice(int vDevType)
        {
            return U3pNewDevice(vDevType);
        }

        /// 
        /// <param name="vDevType"></param>
        public override string TypeToName(int vDevType)
        {

            return C3pFunc.TypeToName(vDevType);
        }

        /// 
        /// <param name="vDevType"></param>
        public static CDevBase U3pNewDevice(int vDevType)
        {

            CDevBase vDev;

            switch (vDevType)
            {
                case C3pDefs.U3p_AcSys:
                    //交流系统  
                    vDev = new C3pDevAcSys();
                    break;
                
                case C3pDefs.U3p_Xf2:
                    //双绕组变压器  
                    vDev = new C3pDevXf2();
                    break;

                case C3pDefs.U3p_Convertor:
                    //换流器  
                    vDev = new C3pDevConvertor();
                    break;

                default:
                    vDev = null;
                    break;

            }//switch

            vDev.Init();

            return vDev;
        }

    }//end C3pDevTBL

}//end namespace DevTBL