///////////////////////////////////////////////////////////
//  CxbRwOne.cs
//  Implementation of the Class CxbRwOne
//  Generated by Enterprise Architect
//  Created on:      09-5ÔÂ-2017 8:08:07
//  Original author: open2
///////////////////////////////////////////////////////////


using Hvdc.MT.xb.Device;
using Yao.BaseFrame.Func;

namespace Hvdc.MT.xb.Rw
{
    public class CxbRwOne : CxbRw
    {

    }//end CxbRwOne

}//end namespace mc