///////////////////////////////////////////////////////////
//  CxbRw.cs
//  Implementation of the Class CxbRw
//  Generated by Enterprise Architect
//  Created on:      09-5ÔÂ-2017 8:08:06
//  Original author: open2
///////////////////////////////////////////////////////////

using Hvdc.MT.xb.Device;
using Yao.BaseFrame.Rw;
using Yao.BaseFrame.Device;

using Yao.BaseFrame.Func;

namespace Hvdc.MT.xb.Rw
{
    public class CxbRw : CRwDev
    {
        protected override void doLoad(CDevBase vDevice)
        {
            CxbDevBase vDev;

            vDev=(CxbDevBase)vDevice;

            base.doLoad(vDevice);

            //
            vDev.PosOrNeg = RwAdo.ReadInt16("PosOrNeg");

        }

        protected override void doSave(CDevBase vDevice)
        {
            CxbDevBase vDev;

            vDev = (CxbDevBase)vDevice;

            base.doSave(vDevice);

            SqlStr = SqlStr + ",";
            SqlParam = SqlParam + ",";

            SqlStr = SqlStr + "PosOrNeg ";
            SqlParam = SqlParam + GetString(vDev.PosOrNeg);
        }

        ////////////////////////////////////
        protected void doLoad0(CxbDevBase vDevice)
        {
            base.doLoad(vDevice);
            //
            vDevice.PosOrNeg = RwAdo.ReadInt16("PosOrNeg");

        }

        protected void doSave0(CxbDevBase vDevice)
        {
            base.doSave(vDevice);

            SqlStr = SqlStr + ",";
            SqlParam = SqlParam + ",";

            SqlStr = SqlStr + "PosOrNeg ";
            SqlParam = SqlParam + GetString(vDevice.PosOrNeg);
        }


    }//end CxbRw

}//end namespace xb