///////////////////////////////////////////////////////////
//  CmcDevBase.cs
//  Implementation of the Class CmcDevBase
//  Generated by Enterprise Architect
//  Created on:      09-5ÔÂ-2017 17:08:08
//  Original author: open2
///////////////////////////////////////////////////////////


using Yao.BaseFrame.Device;

namespace Hvdc.MT.mc.Device
{
    public class CmcDevBase : CDevBase
    {

    }//end CmcDevBase

}//end namespace mcDev