///////////////////////////////////////////////////////////
//  CmcDevOneDot.cs
//  Implementation of the Class CmcDevOneDot
//  Generated by Enterprise Architect
//  Created on:      09-5月-2017 17:08:08
//  Original author: open2
///////////////////////////////////////////////////////////




namespace Hvdc.MT.mc.Device
{
    /// <summary>
    /// 一端点设备
    /// </summary>
    public class CmcDevOneDot : CmcDevBase
    {

        public CmcDevOneDot()
        {
            StaCount = 1;
            dotCount = 1;
        }

    }//end CmcDevOneDot

}//end namespace mcDev