///////////////////////////////////////////////////////////
//  C3pRwMvc.cs
//  Implementation of the class C3pRwMvc
//  Generated by Enterprise Architect
//  Created on:      09-5月-2017 8:08:05
//  Original author: open2
///////////////////////////////////////////////////////////

using Yao.BaseFrame.Rw;

using Hvdc.MT.U3p.Def;

using Hvdc.MT.U3p.DevTBL;
using Yao.BaseFrame.Device;
using Hvdc.MT.U3p.Rw;

namespace Hvdc.MT.U3p.RwMvc
{
    public class C3pRwMvc : CRwMvcAccess
    {
        private C3pHvdcGrid pGrid;
        
        /// 
        /// <param name="vHvdc"></param>
        public void InitGrid(C3pHvdcGrid vGrid)
        {
            pGrid = vGrid;
        }

        protected override void doLoad()
        {
            CRwDev vRw;
            //
            vRw = doNewRw(C3pDefs.U3p_AcSys);
            vRw.OnLoad();

            //
            vRw = doNewRw(C3pDefs.U3p_Convertor);
            vRw.OnLoad();

            //
            vRw = doNewRw(C3pDefs.U3p_Xf2);
            vRw.OnLoad();
                            
        }

        protected override void doSave()
        {
            CRwDev vRw;
            //
            vRw = doNewRw(C3pDefs.U3p_AcSys);
            vRw.OnSave();

            //
            vRw = doNewRw(C3pDefs.U3p_Convertor);
            vRw.OnSave();

            //
            vRw = doNewRw(C3pDefs.U3p_Xf2);
            vRw.OnSave();

        }

        protected override CRwDev doNewRw(int vtblType)
        {
            CRwDev vRw;

            switch (vtblType)
            {
                case C3pDefs.U3p_AcSys:
                    //交流系统  
                    vRw = new C3pRwAcSys();

                    vRw.InitAdo(RwAdo);
                    vRw.InitTable("U3pAcSys");
                    vRw.InitType(C3pDefs.U3p_AcSys, C3pDefs.U3p_AcSys);
                    vRw.InitGrid(pGrid);

                    break;
              
                case C3pDefs.U3p_Xf2:
                    //双绕组变压器  
                    vRw = new C3pRwXf2();

                    vRw.InitAdo(RwAdo);
                    vRw.InitTable("U3pTransformer");
                    vRw.InitType(C3pDefs.U3p_Xf2, C3pDefs.U3p_Xf2);
                    vRw.InitGrid(pGrid);

                    break;

                case C3pDefs.U3p_Convertor:
                    //换流器  
                    vRw = new C3pRwConvertor();

                    vRw.InitAdo(RwAdo);
                    vRw.InitTable("U3pConvertor");
                    vRw.InitType(C3pDefs.U3p_Convertor, C3pDefs.U3p_Convertor);
                    vRw.InitGrid(pGrid);

                    break;

                default:
                    vRw = null;
                    break;

            }

            return vRw;

        }      


    }//end C3pRwMvc

}//end namespace mc
