///////////////////////////////////////////////////////////
//  CmcFunc.cs
//  Implementation of the Class CmcFunc
//  Generated by Enterprise Architect
//  Created on:      09-5月-2017 16:15:35
//  Original author: open2
///////////////////////////////////////////////////////////

using Hvdc.MT.mc.Def;

namespace Hvdc.MT.mc.Func
{
    public static class CmcFunc
    {
        /// 
        /// <param name="vType"></param>
        public static string mcTypeToName(int vType)
        {
            string vStr;

            switch (vType)
            {
                case CmcDef.mc_AcSys:
                    vStr= "交流系统";
                    break;

                case CmcDef.mc_AcF:
                    vStr= "交流滤波器";
                    break;

                case CmcDef.mc_Xf2:
                    vStr= "换流变";
                    break;

                case CmcDef.mc_Convertor:
                    vStr= "换流器";
                    break;

                case CmcDef.mc_DcLine:
                    vStr= "直流极线";
                    break;

                case CmcDef.mc_Ground:
                    vStr= "接地极";
                    break;

                case CmcDef.mc_GroundLine:
                    vStr= "接地极线";
                    break;

                case CmcDef.mc_MetalLine:
                    vStr= "金属回线";
                    break;

                default:
                    vStr= "HvdcDevice";
                    break;

            }//switch

            return vStr;

        }//mcType

    }//end CmcFunc

}//end namespace mc