///////////////////////////////////////////////////////////
//  C3pDevOneDot.cs
//  Implementation of the Class C3pDevOneDot
//  Generated by Enterprise Architect
//  Created on:      09-5月-2017 17:08:08
//  Original author: open2
///////////////////////////////////////////////////////////




namespace Hvdc.MT.U3p.Device
{
    /// <summary>
    /// 一端点设备
    /// </summary>
    public class C3pDevOneDot : C3pDevBase
    {
        public C3pDevOneDot()
        {
            StaCount = 1;
            dotCount = 1;
        }

    }//end C3pDevOneDot

}//end namespace mcDev