///////////////////////////////////////////////////////////
//  C3pDevTwoDot.cs
//  Implementation of the Class C3pDevTwoDot
//  Generated by Enterprise Architect
//  Created on:      09-5月-2017 17:08:08
//  Original author: open2
///////////////////////////////////////////////////////////




namespace Hvdc.MT.U3p.Device
{
    /// <summary>
    /// 双端点设备
    /// </summary>
    public class C3pDevTwoDot : C3pDevBase
    {
        public C3pDevTwoDot()
        {
            StaCount = 1;
            dotCount = 2;
        }

    }//end C3pDevTwoDot

}//end namespace mcDev