///////////////////////////////////////////////////////////
//  CxbDevXf_C.cs
//  Implementation of the Class CxbDevXf_C
//  Generated by Enterprise Architect
//  Created on:      09-5‘¬-2017 17:08:10
//  Original author: open2
///////////////////////////////////////////////////////////

namespace Hvdc.MT.xb.Device
{
    /// <summary>
    /// ±‰—π∆˜‘”…¢µÁ»›
    /// </summary>
    public class CxbDevXf_C : CxbDevShunt
    {

    }//end CxbDevXf_C

}//end namespace xbDev