///////////////////////////////////////////////////////////
//  CxbDevTwoDot.cs
//  Implementation of the Class CxbDevTwoDot
//  Generated by Enterprise Architect
//  Created on:      09-5月-2017 17:08:10
//  Original author: open2
///////////////////////////////////////////////////////////

namespace Hvdc.MT.xb.Device
{
    /// <summary>
    /// 双端点设备
    /// </summary>
    public class CxbDevTwoDot : CxbDevBase
    {
        public CxbDevTwoDot()
        {
            StaCount = 1;
            dotCount = 2;
        }

    }//end CxbDevTwoDot

}//end namespace xbDev