///////////////////////////////////////////////////////////
//  CxbDevDcLine.cs
//  Implementation of the Class CxbDevDcLine
//  Generated by Enterprise Architect
//  Created on:      09-5月-2017 17:08:09
//  Original author: open2
///////////////////////////////////////////////////////////

namespace Hvdc.MT.xb.Device
{
    /// <summary>
    /// 直流线路组合，可能含多个子段
    /// </summary>
    public class CxbDevDcLine : CxbDevGroundLine
    {
        public CxbDevDcLine()
        {
            StaCount = 2;
            dotCount = 0;
        }


    }//end CxbDevDcLine

}//end namespace xbDev