///////////////////////////////////////////////////////////
//  CxbDevPulse_C.cs
//  Implementation of the Class CxbDevPulse_C
//  Generated by Enterprise Architect
//  Created on:      09-5ÔÂ-2017 17:08:10
//  Original author: open2
///////////////////////////////////////////////////////////

namespace Hvdc.MT.xb.Device
{
    /// <summary>
    /// ³å¼¤µçÈÝ
    /// </summary>
    public class CxbDevPulse_C : CxbDevShunt
    {

    }//end CxbDevPulse_C

}//end namespace xbDev