///////////////////////////////////////////////////////////
//  CxbDevBase.cs
//  Implementation of the Class CxbDevBase
//  Generated by Enterprise Architect
//  Created on:      09-5ÔÂ-2017 17:08:09
//  Original author: open2
///////////////////////////////////////////////////////////

using Yao.BaseFrame.Device;

namespace Hvdc.MT.xb.Device
{
    public class CxbDevBase : CDevBase
    {

    }//end CxbDevBase

}//end namespace xbDev