///////////////////////////////////////////////////////////
//  C3pDef.cs
//  Implementation of the Class C3pDef
//  Generated by Enterprise Architect
//  Created on:      09-5ÔÂ-2017 16:56:21
//  Original author: open2
///////////////////////////////////////////////////////////

namespace Hvdc.MT.U3p.Def
{
    public class C3pDefs
    {
        public const int U3p_AcSys = 11;
        public const int U3p_AcF = 12;
        public const int U3p_Xf2 = 13;
        public const int U3p_Convertor = 14;
        public const int U3p_DcLine = 15;
        public const int U3p_GroundLine = 16;
        public const int U3p_MetalLine = 17;
        public const int U3p_Ground = 18;


    }//end C3pDef

    public struct RecAcSysXb
    {
        public int hOrder;
        public double hUrms;
        public double hAngle;

    };
}//end namespace Def