///////////////////////////////////////////////////////////
//  CmcRwMvc.cs
//  Implementation of the Class CmcRwMvc
//  Generated by Enterprise Architect
//  Created on:      09-5ÔÂ-2017 8:08:05
//  Original author: open2
///////////////////////////////////////////////////////////

using Yao.BaseFrame.Rw;
using Yao.BaseFrame.App;


using Hvdc.MT.mc.App;
using Hvdc.MT.xb.App;


namespace Hvdc.MT.Project.Rw
{
    public class CHvdcRwMvc : CRwMvcAccess
    {
        protected override void doLoad()
        {
            string vSQL;

            vSQL = "select * from Hvdc_Project ";
            RwAdo.OpenSQL(vSQL);

            if (RwAdo.Record_Read())
            {
                CMyParams.ProjectName    = RwAdo.ReadString("ProjectName");
                CmcParams.mcStationCount = RwAdo.ReadInt32("mcStationCount");
                CxbParams.xbStationCount = RwAdo.ReadInt32("xbStationCount");
            }
            //
            RwAdo.CloseTBL();

        }

        protected override void doSave()
        {
            string vSQL;
            //
            vSQL = "delete * from Hvdc_Project";
            RwAdo.ExecSQL(vSQL);

            //
            vSQL = "Insert into Hvdc_Project";
            vSQL = vSQL + "( ProjectName, mcStationCount ,xbStationCount ) ";
            vSQL = vSQL + " Values( ";
            vSQL = vSQL + "'" + CMyParams.ProjectName + "'";
            vSQL = vSQL + " , " + CmcParams.mcStationCount.ToString();
            vSQL = vSQL + " , " + CxbParams.xbStationCount.ToString();
            vSQL = vSQL + " ) ";

            //
            RwAdo.ExecSQL(vSQL);

            //
            RwAdo.CloseTBL();


        }


    }//end CHvdcRwMvc

}//end namespace mc