///////////////////////////////////////////////////////////
//  CmcDef.cs
//  Implementation of the Class CmcDef
//  Generated by Enterprise Architect
//  Created on:      09-5月-2017 16:56:21
//  Original author: open2
///////////////////////////////////////////////////////////

namespace Hvdc.MT.mc.Def
{
    public class CmcDef
    {
        public const int mc_AcSys = 11;
        public const int mc_AcF = 12;
        public const int mc_Xf2 = 13;
        public const int mc_Convertor = 14;
        public const int mc_DcLine = 15;
        public const int mc_GroundLine = 16;
        public const int mc_MetalLine = 17;
        public const int mc_Ground = 18;

    }//end CmcDef


    public struct RecUdCustom
    {
        //崔康生20170528-直流电压预设
        public int PdIndex;
        public double Ud21; //双极单阀
        public double Ud22;//双极双阀
        public double Ud11;//单极单阀
    }

    //typedef map<string, struct_mcResultData> mc_ResultMap;

    //崔康生20170528-NewGrid
    public class mcNodeName
    {
        //public static string[] mcNodeNameACF = { };

        //public static string[] mcNodeNameAcSys = { };

        public static string[] mcNodeNameConvertor = { "ConHigh", "ConLow" };

        //public static string[] mcNodeNameXf2 = { };

        public static string[] mcNodeNameGroundLine = { "ConLow", "RdGnd" };

        public static string[] mcNodeNameGround = { "RdGnd" };
    }
}//end namespace Def