///////////////////////////////////////////////////////////
//  CmcDef.cs
//  Implementation of the Class CmcDef
//  Generated by Enterprise Architect
//  Created on:      09-5ÔÂ-2017 16:56:21
//  Original author: open2
///////////////////////////////////////////////////////////

namespace Hvdc.MT.mc.Def
{
    public class CmcDef
    {
        public const int mc_AcSys = 11;
        public const int mc_AcF = 12;
        public const int mc_Xf2 = 13;
        public const int mc_Convertor = 14;
        public const int mc_DcLine = 15;
        public const int mc_GroundLine = 16;
        public const int mc_MetalLine = 17;
        public const int mc_Ground = 18;

    }//end CmcDef


  
    //typedef map<string, struct_mcResultData> mc_ResultMap;

    //´Þ¿µÉú20170528-NewGrid
    public class mcNodeName
    {
        //public static string[] mcNodeNameACF = { };

        //public static string[] mcNodeNameAcSys = { };

        public static string[] mcNodeNameConvertor = { "ConHigh", "ConLow" };

        //public static string[] mcNodeNameXf2 = { };

        public static string[] mcNodeNameGroundLine = { "ConLow", "RdGnd" };

        public static string[] mcNodeNameGround = { "RdGnd" };
    }
}//end namespace Def