///////////////////////////////////////////////////////////
//  CMyVars.cs
//  Implementation of the Class CMyVars
//  Generated by Enterprise Architect
//  Created on:      09-5ÔÂ-2017 16:15:35
//  Original author: open2
///////////////////////////////////////////////////////////

namespace Yao.BaseFrame.App
{
    public static class CMyVars
    {

        public static void Release()
        {

        }

        public static void Clear()
        {

        }

        public static void Init()
        {

            //gbPasVar:=TPasVar.Create;
            //gbPasVar.InitSelf;
        }

    }//end CMyVars

}//end namespace BaseFrame