///////////////////////////////////////////////////////////
//  C3pDevConvertor.cs
//  Implementation of the Class C3pDevConvertor
//  Generated by Enterprise Architect
//  Created on:      09-5ÔÂ-2017 17:08:08
//  Original author: open2
///////////////////////////////////////////////////////////




namespace Hvdc.MT.U3p.Device
{
    /// <summary>
    /// »»Á÷Æ÷
    /// </summary>
    public class C3pDevConvertor : C3pDevTwoDot
    {
        public double[] dAngle;
        public double Std_Angle { get; set; }
        public double Dis_dAngle { get; set; }
        public int StationType { get; set; }

        public C3pDevConvertor()
        {
            dAngle = new double[6];
        }


    }//end C3pDevConvertor

}//end namespace mcDev