///////////////////////////////////////////////////////////
//  CRwMvc.cs
//  Implementation of the Class CRwMvc
//  Generated by Enterprise Architect
//  Created on:      10-5ÔÂ-2017 9:23:38
//  Original author: open2
///////////////////////////////////////////////////////////

using System.Data;
using System.Data.OleDb;

namespace Yao.BaseFrame.dataRw
{
    public class CDataRwMvc
    {
        protected CDataRw RwAdo;
        protected string dbfName;

        public DataSet daSet;

        /// 
        /// <param name="vDbf"></param>
        public virtual void InitAdo(string vDbf)
        {
            dbfName = vDbf;

            daSet = new DataSet();

            RwAdo = new CDataRw(daSet);
            RwAdo.InitDbf(dbfName, "", "", "false");

        }

        public virtual void OnLoad()
        {
            try
            {
                using (RwAdo.OpenDBF())
                {
                    doLoad();

                    //doCopy();

                    //
                    RwAdo.CloseDBF();

                }//
            }
            catch (OleDbException )
            {
                throw;
            }
           

        }

        public virtual void OnSave()
        {
            try
            {
                using (RwAdo.OpenDBF())
                {
                    doSave();
                    //
                    RwAdo.CloseDBF();

                }//
            }
            catch (OleDbException )
            {
                throw;
            }


        }

        protected virtual void doLoad()
        {

        }

        protected virtual void doSave()
        {

        }
    }//end CDataRwMvc

}//end namespace RwBase