///////////////////////////////////////////////////////////
//  CmcRwOne.cs
//  Implementation of the class CmcRwOne
//  Generated by Enterprise Architect
//  Created on:      09-5ÔÂ-2017 8:08:05
//  Original author: open2
///////////////////////////////////////////////////////////

using Hvdc.MT.mc.Device;
using Yao.BaseFrame.Func;

namespace Hvdc.MT.mc.Rw
{
    public class CmcRwOne : CmcRw
    {

    }//end CmcRwOne

}//end namespace mc