///////////////////////////////////////////////////////////
//  CmcRwMetalLine.cs
//  Implementation of the class CmcRwMetalLine
//  Generated by Enterprise Architect
//  Created on:      10-5ÔÂ-2017 16:00:33
//  Original author: open2
///////////////////////////////////////////////////////////


namespace Hvdc.MT.mc.Rw
{
    public class CmcRwMetalLine : CmcRwDcLine
    {

    }//end CmcRwMetalLine

}//end namespace mc
