///////////////////////////////////////////////////////////
//  C3pRwAcSys.cs
//  Implementation of the class C3pRwAcSys
//  Generated by Enterprise Architect
//  Created on:      09-5ÔÂ-2017 8:08:04
//  Original author: open2
///////////////////////////////////////////////////////////

using Hvdc.MT.U3p.Device;
using Yao.BaseFrame.Device;
using Yao.BaseFrame.DevTBL;
using Yao.BaseFrame.Func;

namespace Hvdc.MT.U3p.Rw
{
    public class C3pRwAcSys : C3pRwOne
    {
        public override void OnLoad()
        {
            base.OnLoad();

            doLoad_hData();
        }


        protected override void doLoad(CDevBase vDevice)
        {
            C3pDevAcSys vDev;
            vDev = (C3pDevAcSys)vDevice;

            base.doLoad(vDevice);

            vDev.Rs = RwAdo.ReadDouble("Rs") ;
            vDev.Ls = RwAdo.ReadDouble("Ls") ;
          
        }


        protected void doLoad_hData()
        {
            CDevTBL vTBL;

            vTBL = pGrid.DeviceTBL(tblType);
            foreach (C3pDevAcSys vDev in vTBL.Children())
            {
                //
                doLoad_hData(vDev);

            }//for each
        }


        protected void doLoad_hData(C3pDevAcSys  vDev)
        {
            int vh;
            string vSQL;

            //
            vSQL = "select count(hOrder)as hCount from " + tblName + "_hData ";
            vSQL = vSQL + " where DeviceName = ";
            vSQL = vSQL + " '";
            vSQL = vSQL + vDev.DeviceName;
            vSQL = vSQL + "' ";            

            RwAdo.OpenSQL(vSQL);
            RwAdo.Record_Read();

            vDev.hCount = RwAdo.ReadInt32("hCount");

            //
            vSQL = "select * from " + tblName + "_hData ";
            vSQL = vSQL + " where DeviceName = ";
            vSQL = vSQL + " '";
            vSQL = vSQL + vDev.DeviceName;
            vSQL = vSQL + "' ";
            vSQL = vSQL + " order by DeviceName ,hOrder ";

            RwAdo.OpenSQL(vSQL);

            vh = 0;
            while (RwAdo.Record_Read())
            {
                //cout << "Load---" + tblName + "_hData " << endl;

                vDev.pXb[vh].hOrder = RwAdo.ReadInt32("hOrder");
                vDev.pXb[vh].hUrms = RwAdo.ReadDouble("hUrms");
                vDev.pXb[vh].hAngle = RwAdo.ReadDouble("hAngle");

                //
                vh = vh + 1;

            }//while

            //cout << "   --" << vDev.GetDeviceName() << endl;

            RwAdo.CloseTBL();

        }


        public override void OnSave()
        {
            base.OnSave();

            doSave_hData();
        }

        /// 
        /// <param name="vDevice"></param>
        protected override void doSave(CDevBase vDevice)
        {
            C3pDevAcSys vDev;
            vDev = (C3pDevAcSys)vDevice;

            base.doSave(vDevice);

            SqlStr = SqlStr + ",";
            SqlParam = SqlParam + ",";

            SqlStr = SqlStr + "Rs, ";
            SqlParam = SqlParam + GetString(vDev.Rs) + " , ";
           
            SqlStr = SqlStr + "Ls ";
            SqlParam = SqlParam + GetString(vDev.Ls);

        }


        protected void doSave_hData()
        {
            ///////////////////////////////////////////
            CDevTBL vTBL;

            vTBL = pGrid.DeviceTBL(tblType);
            foreach (C3pDevAcSys vDev in vTBL.Children())
            {
                doSave_hData(vDev);
            }
        }


        protected void doSave_hData(C3pDevAcSys vDev)
        {
            string vSQL;

            vSQL = "delete * from " + tblName + "_hData ";
            vSQL = vSQL + " where DeviceName = ";
            vSQL = vSQL + " '";
            vSQL = vSQL + vDev.DeviceName;
            vSQL = vSQL + "' ";

            RwAdo.ExecSQL(vSQL);

            //
            //cout << " Save --- " + tblName + "_hData " << endl;

            for (int i = 0; i < vDev.hCount; i++)
            {
                //
                SqlStr = "Insert into " + tblName+"_hData";
                SqlParam = "";
                //
                SqlStr = SqlStr + " (";
                SqlParam = SqlParam + " Values ( ";

                SqlStr = SqlStr + "DeviceName, ";
                SqlParam = SqlParam + GetString(vDev.DeviceName) + " , ";

                SqlStr = SqlStr + "hOrder, ";
                SqlParam = SqlParam + GetString(vDev.pXb[i].hOrder) + " , ";

                SqlStr = SqlStr + "hUrms, ";
                SqlParam = SqlParam + GetString(vDev.pXb[i].hUrms) + " , ";

                SqlStr = SqlStr + "hAngle ";
                SqlParam = SqlParam + GetString(vDev.pXb[i].hAngle);

                //
                SqlStr = SqlStr + " ) ";
                SqlParam = SqlParam + " ) ";
                //
                SqlStr = SqlStr + SqlParam;

                //
                RwAdo.ExecSQL(SqlStr);
                //
                //cout << "   --" << vDev.GetDeviceName() << endl;

            }//for

            RwAdo.CloseTBL();

        }


    }//end C3pRwAcSys

}//end namespace mc