///////////////////////////////////////////////////////////
//  CHvdcParams.cs
//  Implementation of the Class CHvdcParams
//  Generated by Enterprise Architect
//  Created on:      09-5ÔÂ-2017 16:15:35
//  Original author: open2
///////////////////////////////////////////////////////////

using Yao.BaseFrame.App;

using Hvdc.MT.mc.App;
using Hvdc.MT.xb.App;
using Hvdc.MT.U3p.App;
using Yao.BaseFrame.Func;
using System;

namespace Hvdc.MT.Project.App
{
    public static class CHvdcParams
    {
        //public static string dbfFile { get; set; }

        public static void Init()
        {
            CMyParams.Init();

            CmcParams.Init();
            CxbParams.Init();

            C3pParams.Init();

            //PRJFile = "..\\..\\..\\..\\DBF\\mcDBF.accdb"; 
           

        }

        public static void Clear()
        {
            CMyParams.Clear();

            CmcParams.Clear();
            CxbParams.Clear();
            C3pParams.Clear();

        }

        public static void SetDbfFile(string vPath)
        {
            CMyParams.PRJFile = vPath + "mcDBF.accdb";

            CmcParams.dbfFile = vPath + "mcDBF.accdb";
            CxbParams.dbfFile = vPath + "xbDBF.accdb";
            C3pParams.dbfFile = vPath + "u3pDBF.accdb";

        }
    }//end CHvdcParams

}//end namespace BaseFrame