///////////////////////////////////////////////////////////
//  C3pStation.cs
//  Implementation of the Class C3pStation
//  Generated by Enterprise Architect
//  Created on:      21-5ÔÂ-2017 7:51:09
//  Original author: open2
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Yao.BaseFrame.DevTBL;
using Hvdc.MT.U3p.Func;
using Hvdc.MT.U3p.Def;

namespace Hvdc.MT.U3p.DevTBL
{
    public class C3pDevStation : CDevStation
    {

        public override void Init()
        {
            int i1, i2;

            i1 = C3pDefs.U3p_AcSys;
            i2 = C3pDefs.U3p_Ground;

            for (int i = i1; i <= i2; i++)
                NewDevTBL(i);
        }

        /// <summary>
        /// @param ="vType"
        /// </summary>
        /// <param name="vDevType"></param>
        public override string TypeToName(int vDevType)
        {
            return C3pFunc.TypeToName(vDevType);
        }

        /// 
        /// <param name="vType"></param>
        public override CDevTBL NewDevTBL(int vType)
        {

            string vName;
            CDevTBL vTBL;

            vName = TypeToName(vType);

            //
            vTBL = new C3pDevTBL();

            vTBL.tblName = vName;
            vTBL.tblType = vType;

            //
            Add(vTBL);

            //
            pTables[vType] = vTBL;

            return vTBL;
        }

    }//end C3pStation

}//end namespace DevTBL