///////////////////////////////////////////////////////////
//  CRwMvcAccess.cs
//  Implementation of the Class CRwMvcAccess
//  Generated by Enterprise Architect
//  Created on:      10-5ÔÂ-2017 9:43:27
//  Original author: open2
///////////////////////////////////////////////////////////

namespace Yao.BaseFrame.Rw
{
    public class CRwMvcAccess : CRwMvc
    {
        public override void InitAdo(string vDbf)
        {
            dbfName = vDbf;

            if (RwAdo == null)
                RwAdo = new CRwAdo_Access();

            RwAdo.InitDbf(dbfName, "", "", "false");

        }

    }//end CRwMvcAccess

}//end namespace RwBase