///////////////////////////////////////////////////////////
//  CxbDevStation.cs
//  Implementation of the Class CxbDevStation
//  Generated by Enterprise Architect
//  Created on:      21-5ÔÂ-2017 7:11:02
//  Original author: open2
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Yao.BaseFrame.DevTBL;
using Hvdc.MT.xb.Def;
using Hvdc.MT.xb.Func;

namespace Hvdc.MT.xb.DevTBL
{
    public class CxbDevStation : CDevStation
    {
        public override void Init()
        {
            int i1, i2;

            i1 = CxbDef.xb_3pVSrc;
            i2 = CxbDef.xb_GroundLine;

            for (int i = i1; i <= i2; i++)
                NewDevTBL(i);
        }

        public override string TypeToName(int vType)
        {

            return CxbFunc.xbTypeToName(vType);
        }

        /// 
        /// <param name="vType"></param>
        public override CDevTBL NewDevTBL(int vType)
        {

            string vName;
            CDevTBL vTBL;

            vName = TypeToName(vType);

            //
            vTBL = new CxbDevTBL();
            vTBL.tblName = vName;
            vTBL.tblType = vType;

            //
            Add(vTBL);

            //
            pTables[vType] = vTBL;

            return vTBL;
        }


    }//end CxbDevStation

}//end namespace DevTBL