///////////////////////////////////////////////////////////
//  C3pVars.cs
//  Implementation of the Class C3pVars
//  Generated by Enterprise Architect
//  Created on:      09-5ÔÂ-2017 16:17:29
//  Original author: open2
///////////////////////////////////////////////////////////

using Hvdc.MT.U3p.DevTBL;
using Hvdc.MT.U3p.Solve;
using System.Collections.Generic;

namespace Hvdc.MT.U3p.App
{
    public static class C3pVars
    {
        public static C3pOrder pOrder;

        public static C3pHvdcGrid pGrid;

        public static void Init()
        {
            pGrid = new C3pHvdcGrid();

            pOrder = new C3pOrder();

        }
        public static void Release()
        {
            //pGrid.Release();
        }

        public static void Clear()
        {
            pGrid.Clear();
        }

        public static void NewGrid()
        {
            IList<string> StaNames = new List<string>();

            StaNames.Add("station1");
            StaNames.Add("station2");
            StaNames.Add("station3");


            pGrid.NewGrid(StaNames);
        }

    }//end C3pVars

}//end namespace U3p