///////////////////////////////////////////////////////////
//  CmcRw.cs
//  Implementation of the class CmcRw
//  Generated by Enterprise Architect
//  Created on:      09-5月-2017 8:08:04
//  Original author: open2
///////////////////////////////////////////////////////////

using Yao.BaseFrame.Rw;
using Yao.BaseFrame.DevTBL;

using Hvdc.MT.mc.Device;
using Hvdc.MT.mc.DevTBL;
using Yao.BaseFrame.Func;
using Yao.BaseFrame.Device;

namespace Hvdc.MT.mc.Rw
{
    /// <summary>
    /// 主回路计算读写
    /// </summary>
    public class CmcRw : CRwDev
    {
    }//end CmcRw

}//end namespace mc