///////////////////////////////////////////////////////////
//  CHvdcMvcs.cs
//  Implementation of the Class CHvdcMvcs
//  Generated by Enterprise Architect
//  Created on:      09-5ÔÂ-2017 16:15:35
//  Original author: open2
///////////////////////////////////////////////////////////


using Hvdc.MT.U3p.Rw;
using Hvdc.MT.U3p.RwMvc;
using Yao.BaseFrame.Device;

namespace Hvdc.MT.U3p.App
{
    public static class C3pMvcs
    {
        public static C3pRwMvc p3pRwMvc;

        public static void Release()
        {
            
        }

        public static void Clear()
        {

        }

        public static void Init()
        {
            p3pRwMvc = new C3pRwMvc();
            p3pRwMvc.InitGrid(C3pVars.pGrid);
        }

        public static void OnLoad()
        {
            p3pRwMvc.InitAdo(C3pParams.dbfFile);
            p3pRwMvc.OnLoad(C3pParams.dbfFile);

            //
            C3pVars.pGrid.AddToStation();
        }

        public static void OnSave()
        {
            p3pRwMvc.InitAdo(C3pParams.dbfFile);
            p3pRwMvc.OnSave(C3pParams.dbfFile);
        }


        public static void OnLoad(string vdbf)
        {
            p3pRwMvc.InitAdo(vdbf);
            p3pRwMvc.OnLoad(vdbf);

            //
            C3pVars.pGrid.AddToStation();
        }

        public static void OnSave(string vdbf)
        {
            p3pRwMvc.InitAdo(vdbf);
            p3pRwMvc.OnSave(vdbf);
        }

        public static void OnLoad(int vtblType)
        {
            p3pRwMvc.InitAdo(C3pParams.dbfFile);
            p3pRwMvc.OnLoad(vtblType);
            //
            C3pVars.pGrid.AddToStation();
        }

        public static void OnSave(int vtblType)
        {
            p3pRwMvc.InitAdo(C3pParams.dbfFile);
            p3pRwMvc.OnSave(vtblType);
        }

        public static void OnLoad(int vtblType, string vDevicName)
        {
            p3pRwMvc.InitAdo(C3pParams.dbfFile);
            p3pRwMvc.OnLoad(vtblType, vDevicName);
        }

        public static void OnSave(int vtblType, CDevBase vDev)
        {
            p3pRwMvc.InitAdo(C3pParams.dbfFile);
            p3pRwMvc.OnSave(vtblType, vDev);
        }


        public static void OnLoadOrder()
        {
            C3pRwOrderMvc vRwMvc;

            vRwMvc = new C3pRwOrderMvc();

            vRwMvc.InitAdo(C3pParams.dbfFile);
            vRwMvc.InitOrder(C3pVars.pOrder);
            vRwMvc.OnLoad(C3pParams.dbfFile);

        }

        public static void OnSaveOrder()
        {
            C3pRwOrderMvc vRwMvc;

            vRwMvc = new C3pRwOrderMvc();

            vRwMvc.InitAdo(C3pParams.dbfFile);
            vRwMvc.InitOrder(C3pVars.pOrder);
            vRwMvc.OnSave(C3pParams.dbfFile);

        }


    }//end CHvdcMvcs

}//end namespace BaseFrame