///////////////////////////////////////////////////////////
//  CMyDef.cs
//  Implementation of the Class CMyDef
//  Generated by Enterprise Architect
//  Created on:      09-5ÔÂ-2017 16:56:21
//  Original author: open2
///////////////////////////////////////////////////////////

namespace Yao.BaseFrame.Def
{
    public static class CMyDef
    {

    }//end CMyDef

}//end namespace Def