///////////////////////////////////////////////////////////
//  CmcRwXf2.cs
//  Implementation of the class CmcRwXf2
//  Generated by Enterprise Architect
//  Created on:      09-5ÔÂ-2017 8:08:05
//  Original author: open2
///////////////////////////////////////////////////////////


using Hvdc.MT.mc.dataRw;
using Hvdc.MT.mc.Device;
using Yao.BaseFrame.Device;

namespace Hvdc.MT.mc.Rw
{
    public class CmcDataRwXf2 : CmcDataRwTwo
    {
        protected override void doLoad(CDevBase vDevice)
        {
            CmcDevXf2 vDev;
            vDev = (CmcDevXf2)vDevice;

            base.doLoad(vDevice);

            vDev.FixedURef  = RwAdo.ReadDouble("FixedURef") ;
            vDev.FixedUType = RwAdo.ReadInt32("FixedUType");

            vDev.AngleMax = RwAdo.ReadDouble("AngleMax") ;
            vDev.AngleMin = RwAdo.ReadDouble("AngleMin") ;
     
            vDev.TapCtrlType = RwAdo.ReadInt32("TapCtrlType") ;
            vDev.TapN = RwAdo.ReadInt32("TapN");
            vDev.TapMax = RwAdo.ReadInt32("TapMax") ;
            vDev.TapMin = RwAdo.ReadInt32("TapMin") ;
            vDev.TapSetup = RwAdo.ReadDouble("TapSetup") ;

            vDev.Ukp = RwAdo.ReadDouble("Ukp") ;
            vDev.Urp = RwAdo.ReadDouble("Urp") ;

            vDev.TkN = RwAdo.ReadDouble("TkN") ;
            vDev.UacN = RwAdo.ReadDouble("UacN") ;
            vDev.UvN = RwAdo.ReadDouble("UvN") ;
            vDev.UvMax = RwAdo.ReadDouble("UvMax") ;

        }

        /// 
        /// <param name="vDevice"></param>
        protected override void doSave(CDevBase vDevice)
        {
            CmcDevXf2 vDev;
            vDev = (CmcDevXf2)vDevice;

            base.doSave(vDevice);

            RwAdo.SaveField("FixedURef", vDev.FixedURef) ;
            RwAdo.SaveField("FixedUType", vDev.FixedUType) ;

            RwAdo.SaveField("AngleMax", vDev.AngleMax) ;
            RwAdo.SaveField("AngleMin", vDev.AngleMin) ;

            RwAdo.SaveField("TapCtrlType", vDev.TapCtrlType) ;
            RwAdo.SaveField("TapN", vDev.TapN) ;
            RwAdo.SaveField("TapMax", vDev.TapMax) ;
            RwAdo.SaveField("TapMin", vDev.TapMin) ;
            RwAdo.SaveField("TapSetup", vDev.TapSetup) ;

            RwAdo.SaveField("Ukp", vDev.Ukp) ;
            RwAdo.SaveField("Urp", vDev.Urp) ;

            RwAdo.SaveField("TkN", vDev.TkN) ;
            RwAdo.SaveField("UacN", vDev.UacN) ;
            RwAdo.SaveField("UvN", vDev.UvN) ;
            RwAdo.SaveField("UvMax", vDev.UvMax);

        }

    }//end CmcRwXf2

}//end namespace mc