///////////////////////////////////////////////////////////
//  CmcRwGroundLine.cs
//  Implementation of the class CmcRwGroundLine
//  Generated by Enterprise Architect
//  Created on:      09-5ÔÂ-2017 8:08:05
//  Original author: open2
///////////////////////////////////////////////////////////

namespace Hvdc.MT.mc.Rw
{
    public class CmcDataRwGroundLine : CmcDataRwDcLine
    {
        
    }//end CmcRwGroundLine

}//end namespace mc