///////////////////////////////////////////////////////////
//  CxbDevOneDot.cs
//  Implementation of the Class CxbDevOneDot
//  Generated by Enterprise Architect
//  Created on:      09-5月-2017 17:08:10
//  Original author: open2
///////////////////////////////////////////////////////////

namespace Hvdc.MT.xb.Device
{
    /// <summary>
    /// 一端点设备
    /// </summary>
    public class CxbDevOneDot : CxbDevBase
    {
        public CxbDevOneDot()
        {
            StaCount = 1;
            dotCount = 1;
        }

    }//end CxbDevOneDot

}//end namespace xbDev