///////////////////////////////////////////////////////////
//  CxbDevDCF.cs
//  Implementation of the Class CxbDevDCF
//  Generated by Enterprise Architect
//  Created on:      09-5月-2017 17:08:09
//  Original author: open2
///////////////////////////////////////////////////////////

namespace Hvdc.MT.xb.Device
{
    /// <summary>
    /// 直流滤波器组合，含有多个branch子设备
    /// </summary>
    public class CxbDevDCF : CxbDev_Tree
    {
        /// <summary>
        /// 滤波器类型:
        /// 单调谐、双调谐、三调谐等
        /// </summary>
        protected int f_DCFType;
        /// <summary>
        /// 最大频率偏差
        /// </summary>
        protected double f_MaxFreqDelta = 0;
        /// <summary>
        /// 最小频率偏差
        /// </summary>
        protected double f_MinFreqDelta = 0;
        /// <summary>
        /// 随机偏差时的样本数
        /// </summary>
        private int f_SampleNum = 0;

        /// <summary>
        /// 随机偏差时的样本数
        /// </summary>
        public int SampleNum
        {
            get
            {
                return f_SampleNum;
            }
            set
            {
                f_SampleNum = value;
            }
        }

        /// <summary>
        /// 最小频率偏差
        /// </summary>
        public double MinFreqDelta
        {
            get
            {
                return f_MinFreqDelta;
            }
            set
            {
                f_MinFreqDelta = value;
            }
        }

        /// <summary>
        /// 最大频率偏差
        /// </summary>
        public double MaxFreqDelta
        {
            get
            {
                return f_MaxFreqDelta;
            }
            set
            {
                f_MaxFreqDelta = value;
            }
        }

        /// <summary>
        /// 滤波器类型:
        /// 单调谐、双调谐、三调谐等
        /// </summary>
        public int DCFType
        {
            get
            {
                return f_DCFType;
            }
            set
            {
                f_DCFType = value;
            }
        }

    }//end CxbDevDCF

}//end namespace xbDev