///////////////////////////////////////////////////////////
//  CxbDevDCF_RLC.cs
//  Implementation of the Class CxbDevDCF_RLC
//  Generated by Enterprise Architect
//  Created on:      09-5月-2017 17:08:09
//  Original author: open2
///////////////////////////////////////////////////////////

namespace Hvdc.MT.xb.Device
{
    public class CxbDevDCF_RLC : CxbDevBranch
    {
        public CxbDevDCF_RLC()
        {
            StaCount = 1;
            dotCount = 2;
        }
        /// <summary>
        /// 输入参数，正负偏差
        /// </summary>
        protected double f_MaxCDelta;
        protected double f_MaxLDelta;
        protected double f_MaxRDelta;
        protected double f_MinCDelta;
        protected double f_MinLDelta;
        protected double f_MinRDelta;
        protected double f_MaxFreqDelta;
        protected double f_MinFreqDelta;

        /// <summary>
        /// 输入参数，正负偏差
        /// </summary>
        public double MaxCDelta
        {
            get
            {
                return f_MaxCDelta;
            }
            set
            {
                f_MaxCDelta = value;
            }
        }

        public double MaxLDelta
        {
            get
            {
                return f_MaxLDelta;
            }
            set
            {
                f_MaxLDelta = value;
            }
        }

        public double MaxRDelta
        {
            get
            {
                return f_MaxRDelta;
            }
            set
            {
                f_MaxRDelta = value;
            }
        }

        public double MinCDelta
        {
            get
            {
                return f_MinCDelta;
            }
            set
            {
                f_MinCDelta = value;
            }
        }

        public double MinLDelta
        {
            get
            {
                return f_MinLDelta;
            }
            set
            {
                f_MinLDelta = value;
            }
        }

        public double MinRDelta
        {
            get
            {
                return f_MinRDelta;
            }
            set
            {
                f_MinRDelta = value;
            }
        }

        public double MaxFreqDelta
        {
            get
            {
                return f_MaxFreqDelta;
            }
            set
            {
                f_MaxFreqDelta = value;
            }
        }

        public double MinFreqDelta
        {
            get
            {
                return f_MinFreqDelta;
            }
            set
            {
                f_MinFreqDelta = value;
            }
        }

    }//end CxbDevDCF_RLC

}//end namespace xbDev