///////////////////////////////////////////////////////////
//  CxbDevTrap.cs
//  Implementation of the Class CxbDevTrap
//  Generated by Enterprise Architect
//  Created on:      09-5月-2017 17:08:10
//  Original author: open2
///////////////////////////////////////////////////////////

namespace Hvdc.MT.xb.Device
{
    /// <summary>
    /// 阻波器组合,含有多个branch子设备
    /// </summary>
    public class CxbDevTrap : CxbDev_Tree
    {

    }//end CxbDevTrap

}//end namespace xbDev