///////////////////////////////////////////////////////////
//  C3pRwXf2.cs
//  Implementation of the class C3pRwXf2
//  Generated by Enterprise Architect
//  Created on:      09-5ÔÂ-2017 8:08:05
//  Original author: open2
///////////////////////////////////////////////////////////


using Hvdc.MT.U3p.Device;
using Yao.BaseFrame.Device;
using Yao.BaseFrame.Func;

namespace Hvdc.MT.U3p.Rw
{
    public class C3pRwXf2 : C3pRwTwo
    {
        protected override void doLoad(CDevBase vDevice)
        {
            C3pDevXf2 vDev;
            vDev = (C3pDevXf2)vDevice;

            base.doLoad(vDevice);

            vDev.Ukp = RwAdo.ReadDouble("Ukp");
            vDev.Urp = RwAdo.ReadDouble("Urp");

            vDev.SN = RwAdo.ReadDouble("SN");
            vDev.TkN = RwAdo.ReadDouble("TkN");
            vDev.UacN = RwAdo.ReadDouble("UacN");
            vDev.UvN = RwAdo.ReadDouble("UvN");

            vDev.PhaseShift = RwAdo.ReadDouble("PhaseShift");

            vDev.dTkN = RwAdo.ReadDouble("dTkN");
            //vDev.Std_Lt = RwAdo.ReadDouble("Std_Lt");
            //vDev.Dis_dLt = RwAdo.ReadDouble("Dis_dLt");

            vDev.dLtA = RwAdo.ReadDouble("deltaLtA");
            vDev.dLtB = RwAdo.ReadDouble("deltaLtB");
            vDev.dLtC = RwAdo.ReadDouble("deltaLtC");

        }

        /// 
        /// <param name="vDevice"></param>
        protected override void doSave(CDevBase vDevice)
        {
            C3pDevXf2 vDev;
            vDev = (C3pDevXf2)vDevice;

            base.doSave(vDevice);


            SqlStr = SqlStr + ",";
            SqlParam = SqlParam + ",";

            SqlStr = SqlStr + "Ukp, ";
            SqlParam = SqlParam + GetString(vDev.Ukp) + ",";

            SqlStr = SqlStr + "Urp, ";
            SqlParam = SqlParam + GetString(vDev.Urp) + ",";


            SqlStr = SqlStr + "SN, ";
            SqlParam = SqlParam + GetString(vDev.SN) + ",";

            SqlStr = SqlStr + "TkN, ";
            SqlParam = SqlParam + GetString(vDev.TkN) + ",";

            SqlStr = SqlStr + "UacN, ";
            SqlParam = SqlParam + GetString(vDev.UacN) + ",";

            SqlStr = SqlStr + "UvN, ";
            SqlParam = SqlParam + GetString(vDev.UvN) + ",";

            SqlStr = SqlStr + "PhaseShift, ";
            SqlParam = SqlParam + GetString(vDev.PhaseShift) + ",";

            SqlStr = SqlStr + "dTkN, ";
            SqlParam = SqlParam + GetString(vDev.dTkN) + ",";

            //SqlStr = SqlStr + "Std_Lt, ";
            //SqlParam = SqlParam + GetString(vDev.Std_Lt) + ",";

            //SqlStr = SqlStr + "Dis_dLt, ";
            //SqlParam = SqlParam + GetString(vDev.Dis_dLt) + ",";

            SqlStr = SqlStr + "deltaLtA, ";
            SqlParam = SqlParam + GetString(vDev.dLtA) + ",";

            SqlStr = SqlStr + "deltaLtB, ";
            SqlParam = SqlParam + GetString(vDev.dLtB) + ",";

            SqlStr = SqlStr + "deltaLtC ";
            SqlParam = SqlParam + GetString(vDev.dLtC);

        }

    }//end C3pRwXf2

}//end namespace mc