///////////////////////////////////////////////////////////
//  CxbDevShunt.cs
//  Implementation of the Class CxbDevShunt
//  Generated by Enterprise Architect
//  Created on:      09-5月-2017 17:08:10
//  Original author: open2
///////////////////////////////////////////////////////////

namespace Hvdc.MT.xb.Device
{
    /// <summary>
    /// RLC并联支路
    /// </summary>
    public class CxbDevShunt : CxbDevOneDot
    {

        /// <summary>
        /// 电阻
        /// </summary>
        protected double f_Zr;
        /// <summary>
        /// 电感
        /// </summary>
        protected double f_Z_L;
        /// <summary>
        /// 电容
        /// </summary>
        protected double f_Z_C;
        /// <summary>
        /// 感抗
        /// </summary>
        protected double f_Zx_L;
        /// <summary>
        /// 容抗
        /// </summary>
        protected double f_Zx_C;

        /// <summary>
        /// 容抗
        /// </summary>
        public double Zx_C
        {
            get
            {
                return f_Zx_C;
            }
            set
            {
                f_Zx_C = value;
            }
        }

        /// <summary>
        /// 感抗
        /// </summary>
        public double Zx_L
        {
            get
            {
                return f_Zx_L;
            }
            set
            {
                f_Zx_L = value;
            }
        }

        /// <summary>
        /// 电感
        /// </summary>
        public double Z_L
        {
            get
            {
                return f_Z_L;
            }
            set
            {
                f_Z_L = value;
            }
        }

        /// <summary>
        /// 电阻
        /// </summary>
        public double Zr
        {
            get
            {
                return f_Zr;
            }
            set
            {
                f_Zr = value;
            }
        }

        /// <summary>
        /// 电容
        /// </summary>
        public double Z_C
        {
            get
            {
                return f_Z_C;
            }
            set
            {
                f_Z_C = value;
            }
        }

    }//end CxbDevShunt

}//end namespace xbDev