///////////////////////////////////////////////////////////
//  CxbDevGround.cs
//  Implementation of the Class CxbDevGround
//  Generated by Enterprise Architect
//  Created on:      09-5月-2017 17:08:09
//  Original author: open2
///////////////////////////////////////////////////////////

namespace Hvdc.MT.xb.Device
{
    /// <summary>
    /// 接地电阻
    /// </summary>
    public class CxbDevGround : CxbDevShunt
    {

    }//end CxbDevGround

}//end namespace xbDev