///////////////////////////////////////////////////////////
//  CxbDevGroundLine_Seg.cs
//  Implementation of the Class CxbDevGroundLine_Seg
//  Generated by Enterprise Architect
//  Created on:      09-5月-2017 17:08:10
//  Original author: open2
///////////////////////////////////////////////////////////

using Hvdc.MT.xb.Def;

namespace Hvdc.MT.xb.Device
{
    /// <summary>
    /// 接地极线
    /// </summary>
    public class CxbDevGroundLine_Seg : CxbDevBase
    {
        public CxbDevGroundLine_Seg()
        {
            StaCount = 1;
            dotCount = 4;

            LineModel.Hspace = new double[3];
            LineModel.Height = new double[3];
            LineModel.Sag    = new double[3];
        }

        public CxbDef.xbLineModel LineModel;
 

    }//end CxbDevGroundLine_Seg

}//end namespace xbDev