///////////////////////////////////////////////////////////
//  CxbRwTwo.cs
//  Implementation of the Class CxbRwTwo
//  Generated by Enterprise Architect
//  Created on:      09-5ÔÂ-2017 8:08:07
//  Original author: open2
///////////////////////////////////////////////////////////

using Hvdc.MT.xb.Device;
using Yao.BaseFrame.Func;
using Yao.BaseFrame.Rw;

namespace Hvdc.MT.xb.Rw
{
    public class CxbRwTwo : CxbRw
    {
    }//end CxbRwTwo

}//end namespace mc