///////////////////////////////////////////////////////////
//  C3pDevAcSys.cs
//  Implementation of the Class C3pDevAcSys
//  Generated by Enterprise Architect
//  Created on:      09-5月-2017 17:08:07
//  Original author: open2
///////////////////////////////////////////////////////////



using Hvdc.MT.U3p.Def;

namespace Hvdc.MT.U3p.Device
{
    /// <summary>
    /// 主回路 交流系统
    /// </summary>
    public class C3pDevAcSys : C3pDevOneDot
    {                
        public double Rs { get; set; }
        public double Ls { get; set; }

        public RecAcSysXb[] pXb;

        public int f_hCount;
        public int hCount
        {
            get
            {
                return f_hCount;
            }
            set
            {
                f_hCount = value;

                pXb = new RecAcSysXb[value];

            }

        }

    }//end C3pDevAcSys

}//end namespace mcDev