///////////////////////////////////////////////////////////
//  CmcRwAcSys.cs
//  Implementation of the class CmcRwAcSys
//  Generated by Enterprise Architect
//  Created on:      09-5ÔÂ-2017 8:08:04
//  Original author: open2
///////////////////////////////////////////////////////////

using Hvdc.MT.mc.Device;
using Yao.BaseFrame.Device;
using Yao.BaseFrame.Func;

namespace Hvdc.MT.mc.Rw
{
    public class CmcRwAcSys : CmcRwOne
    {
        protected override void doLoad(CDevBase vDevice)
        {
            CmcDevAcSys vDev;
            vDev = (CmcDevAcSys)vDevice;

            base.doLoad(vDevice);

            vDev.QfMinN = RwAdo.ReadDouble("QfMinN") ;
            vDev.QfMaxN = RwAdo.ReadDouble("QfMaxN") ;

            vDev.QinMax = RwAdo.ReadDouble("QinMax") ;
            vDev.QoutMax = RwAdo.ReadDouble("QoutMax") ;

            vDev.UacExMin = RwAdo.ReadDouble("UacExMin") ;
            vDev.UacMax = RwAdo.ReadDouble("UacMax") ;
            vDev.UacMin = RwAdo.ReadDouble("UacMin") ;
            vDev.UacN = RwAdo.ReadDouble("UacN") ;

        }

        /// 
        /// <param name="vDevice"></param>
        protected override void doSave(CDevBase vDevice)
        {
            CmcDevAcSys vDev;
            vDev = (CmcDevAcSys)vDevice;

            base.doSave(vDevice);

            SqlStr = SqlStr + ",";
            SqlParam = SqlParam + ",";

            SqlStr = SqlStr + "QfMinN, ";
            SqlParam = SqlParam + GetString(vDev.QfMinN) + " , ";

            SqlStr = SqlStr + "QfMaxN, ";
            SqlParam = SqlParam + GetString(vDev.QfMaxN) + " , ";

            SqlStr = SqlStr + "QinMax, ";
            SqlParam = SqlParam + GetString(vDev.QinMax) + " , ";

            SqlStr = SqlStr + "QoutMax, ";
            SqlParam = SqlParam + GetString(vDev.QoutMax) + " , ";

            SqlStr = SqlStr + "UacExMin, ";
            SqlParam = SqlParam + GetString(vDev.UacExMin) + " , ";

            SqlStr = SqlStr + "UacMax, ";
            SqlParam = SqlParam + GetString(vDev.UacMax) + " , ";

            SqlStr = SqlStr + "UacMin, ";
            SqlParam = SqlParam + GetString(vDev.UacMin) + " , ";

            SqlStr = SqlStr + "UacN ";
            SqlParam = SqlParam + GetString(vDev.UacN);


        }

    }//end CmcRwAcSys

}//end namespace mc