///////////////////////////////////////////////////////////
//  CxbDef.cs
//  Implementation of the Class CxbDef
//  Generated by Enterprise Architect
//  Created on:      09-5月-2017 16:56:21
//  Original author: open2
///////////////////////////////////////////////////////////


using System.Collections.Generic;

namespace Hvdc.MT.xb.Def
{
    public class CxbDef
    {
        public const int xb_3pVSrc = 1;
        public const int xb_PbDKQ = 2;
        public const int xb_DCF = 3;
        public const int xb_DcLine_Seg = 4;
        public const int xb_GroundLine_Seg = 5;
        public const int xb_Ground = 6;
        public const int xb_MetalLine = 7;
        public const int xb_XfC = 8;
        public const int xb_CoupleC = 9;
        public const int xb_PulseC = 10;
        public const int xb_Shunt = 11;
        public const int xb_Branch = 12;
        public const int xb_Trap = 13;
        public const int xb_Monitor = 14;
        public const int xb_DCF_RLC = 15;
        public const int xb_DCLine = 16;
        public const int xb_GroundLine = 17;

        //
        public const int hMax = 60;


        public struct xbLineModel
        {
            public double Leng;//线路长度
            public int WireCount;//直流线路中输电线和避雷线总数

            public double[] Hspace;//导线水平间距

            public double[] Height;//导线高度


            public double L_CondRadius; //传输线单根导体半径
            public double G_CondRadius;//避雷线单导体半径

            public double[] Sag;     //传输线弧垂


            public int L_CondType;//传输线电导率给定方式
            public double L_CondValue;//计算电导率对应方式的给定值

            public int G_CondType;//避雷线电导率给定方式
            public double G_CondValue;//计算电导率对应方式的给定值

            public int L_SplitAmount;//传输线分裂数
            public int G_SplitAmount;//避雷线分裂数


            public double L_BundleSpace;//传输线分裂间距
            public double G_BundleSpace;//避雷线分裂间距

            public double SoilRe;  //土壤电阻率
        }

        /// <summary>
        /// ////////////////////////
        /// 
        public static string xb_pbdkq_Pole1 = "极线1";
        public static string xb_pbdkq_Pole2 = "极线2";
        public static string xb_pbdkq_N1 = "中性线1";
        public static string xb_pbdkq_N2 = "中性线2";
        public static string xb_XfC_YY = "YY杂散电容";
        public static string xb_XfC_YD = "YD杂散电容";
         
    }//end CxbDef

}//end namespace Def